Repository grafana/profiles-drilldown, pull requests merged in 2024-11, with the labels that each got.

#255 fix(ExplorationSelector): Fix background color
  src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/components/ui/ExplorationTypeSelector.tsx
Labels: fix

#254 fix(DiffView): Clicking on "Auto-select" selects a 25% range
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneComparePanel/SceneComparePanel.tsx
Labels: fix

#256 fix(OnboardingModal): Change Grafana Agent to Grafana Alloy
  src/app/components/Onboarding/ui/OnboardingModal.tsx
Labels: fix

#257 fix(DiffView): Fix incorrect preset label
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/ScenePresetsPicker/ScenePresetsPicker.tsx
Labels: fix

#258 fix(DiffView): Disable AI button when no selections
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneDiffFlameGraph/SceneDiffFlameGraph.tsx
Labels: fix

#259 fix(DiffView): Fix headers wrap
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneComparePanel/SceneComparePanel.tsx
Labels: fix

#262 docs(Contributing): Fix repo URL
  docs/CONTRIBUTING.md
Labels: type/docs

#275 feat(Export): Clarify that export to flamegraph.com will create a public URL
  e2e/fixtures/pages/ExploreProfilesPage.ts
  e2e/tests/settings-view/settings-view.spec.ts
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneExportMenu/SceneExportMenu.tsx
  src/pages/SettingsView/SettingsView.tsx
  src/shared/components/FlameGraph/components/ExportData.tsx
  src/shared/components/FlameGraph/components/ExportMenu.tsx
Labels: feat

#265 docs: Update screenshots
  docs/sources/choose-a-view/index.md
  docs/sources/images/explore-profiles-diff-flamegraph.png
  docs/sources/images/explore-profiles-exploration-bar.png
  docs/sources/images/explore-profiles-favorites.png
  docs/sources/images/explore-profiles-flamegraph-2.png
  docs/sources/images/explore-profiles-flamegraph.png
  docs/sources/images/explore-profiles-homescreen.png
  docs/sources/images/explore-profiles-labels-compare.png
  docs/sources/images/explore-profiles-labels-expand.png
  docs/sources/images/explore-profiles-labels-include-exclude.png
  docs/sources/images/explore-profiles-labels.png
  docs/sources/images/explore-profiles-profile-types.png
  docs/sources/images/explore-profiles-select-profile.png
  docs/sources/images/explore-profiles-view-bar.png
  docs/sources/investigate/index.md
Labels: type/docs

#264 refactor(*): Improve error tracking
  .eslintrc
  src/app/App.tsx
  src/app/components/Routes/Routes.tsx
  src/app/infrastructure/__tests__/faro.spec.ts
  src/app/infrastructure/faro.ts
  src/app/ui/ErrorPage.tsx
  src/pages/AdHocView/domain/useUploadFile.ts
  src/pages/ProfilesExplorerView/components/SceneAiPanel/SceneAiPanel.tsx
  src/pages/ProfilesExplorerView/components/SceneAiPanel/components/AiButton/infrastructure/useFetchLlmPluginStatus.ts
  src/pages/ProfilesExplorerView/components/SceneAiPanel/components/AiReply.tsx
  src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/SceneByVariableRepeaterGrid.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneDiffFlameGraph/SceneDiffFlameGraph.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/domain/behaviours/syncYAxis.ts
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneExportMenu/SceneExportMenu.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneFunctionDetailsPanel/SceneFunctionDetailsPanel.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneFunctionDetailsPanel/components/AiSuggestionsPanel/AiSuggestionsPanel.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneFunctionDetailsPanel/components/GitHubContextProvider/GitHubContextProvider.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneFunctionDetailsPanel/components/GitHubContextProvider/domain/githubLogin.ts
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneFunctionDetailsPanel/components/GitHubContextProvider/domain/usePollGitHubPopup.ts
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneFunctionDetailsPanel/components/GitHubContextProvider/infrastructure/GitSessionCookie.ts
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneFunctionDetailsPanel/components/GitHubContextProvider/infrastructure/PrivateVcsClient.ts
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneFunctionDetailsPanel/components/GitHubContextProvider/infrastructure/__tests__/GitSessionCookieManager.spec.ts
  src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/components/SceneGroupByLabels/components/SceneLabelValuesGrid/SceneLabelValuesGrid.tsx
  src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/SceneProfilesExplorer.tsx
  src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/components/domain/useHeader.ts
  src/pages/ProfilesExplorerView/domain/variables/GroupByVariable/GroupByVariable.tsx
  src/pages/ProfilesExplorerView/domain/variables/ProfileMetricVariable.tsx
  src/pages/ProfilesExplorerView/domain/variables/ServiceNameVariable/ServiceNameVariable.tsx
  src/pages/ProfilesExplorerView/infrastructure/labels/LabelsDataSource.ts
  src/pages/ProfilesExplorerView/infrastructure/series/http/formatSeriesResponse.ts
  src/pages/SettingsView/domain/useSettingsView.ts
  src/shared/components/FlameGraph/components/domain/useExportMenu.ts
  src/shared/components/QueryBuilder/domain/helpers/logger.ts
  src/shared/components/QueryBuilder/domain/services.ts
  src/shared/domain/displayStatus.ts
  src/shared/domain/url-params/useMaxNodesFromUrl.ts
  src/shared/infrastructure/http/ApiClient.ts
  src/shared/infrastructure/profile-metrics/getProfileMetric.ts
  src/shared/infrastructure/tracking/__tests__/getEnvironment.spec.ts
  src/shared/infrastructure/tracking/__tests__/logger.spec.ts
  src/shared/infrastructure/tracking/faro/__tests__/faro.spec.ts
  src/shared/infrastructure/tracking/faro/faro-environments.ts
  src/shared/infrastructure/tracking/faro/faro.ts
  src/shared/infrastructure/tracking/faro/getFaroEnvironment.ts
  src/shared/infrastructure/tracking/getEnvironment.ts
  src/shared/infrastructure/tracking/logger.ts
  src/shared/infrastructure/userStorage.ts
  src/shared/ui/InlineBanner.tsx
Labels: refactor

#277 fix(Tracking): Use custom reporter
  docs/sources/choose-a-view/index.md
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneExportMenu/SceneExportMenu.tsx
  src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/components/domain/useHeader.ts
  src/pages/ProfilesExplorerView/domain/variables/FiltersVariable/FiltersVariable.tsx
  src/shared/domain/reportInteraction.ts
Labels: fix

#276 fix(QueryBuilder): Prevent invalid filters to be used after parsing URL
  src/pages/ProfilesExplorerView/domain/variables/FiltersVariable/FiltersVariable.tsx
  src/pages/ProfilesExplorerView/domain/variables/FiltersVariable/__tests__/filter-ops.spec.ts
  src/pages/ProfilesExplorerView/domain/variables/FiltersVariable/filters-ops.ts
Labels: fix

#278 fix(Tracking): Ensure select action type is tracked
  src/pages/ProfilesExplorerView/components/SceneExploreAllServices/SceneExploreAllServices.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreFavorites/SceneExploreFavorites.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/SceneExploreServiceFlameGraph.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/SceneExploreServiceLabels.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/components/SceneGroupByLabels/SceneGroupByLabels.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceProfileTypes/SceneExploreServiceProfileTypes.tsx
  src/pages/ProfilesExplorerView/domain/actions/SelectAction.tsx
  src/pages/ProfilesExplorerView/domain/variables/GroupByVariable/GroupByVariable.tsx
  src/shared/domain/__tests__/reportInteraction.spec.ts
  src/shared/domain/reportInteraction.ts
Labels: fix

#282 refactor(Faro): Remove tracing instrumentation
  package.json
  src/shared/infrastructure/tracking/faro/__tests__/faro.spec.ts
  src/shared/infrastructure/tracking/faro/faro.ts
  yarn.lock
Labels: refactor

#284 fix(ProfileTypesView): Load last used service name only if it's not provided in the URL
  src/pages/ProfilesExplorerView/domain/variables/ServiceNameVariable/ServiceNameVariable.tsx
Labels: fix

#286 build(Playwright): Upgrade to v1.49.0
  Dockerfile.plugin.e2e
  package.json
  yarn.lock
Labels: build

#287 feat(*): Upgrade Grafana to v11.3.0
  docker-compose.e2e.yaml
  docker-compose.local.yaml
  docker-compose.remote.yaml
  docker-compose.yaml
  e2e/tests/all-services-view/all-services.spec.ts-snapshots/All-services-view-Layout-switcher-1-chromium-linux.png
  e2e/tests/all-services-view/all-services.spec.ts-snapshots/All-services-view-Main-UI-elements-1-chromium-linux.png
  e2e/tests/all-services-view/all-services.spec.ts-snapshots/All-services-view-Panel-actions-Favorite-action-1-chromium-linux.png
  e2e/tests/all-services-view/all-services.spec.ts-snapshots/All-services-view-Panel-actions-Labels-action-1-chromium-linux.png
  e2e/tests/all-services-view/all-services.spec.ts-snapshots/All-services-view-Panel-actions-Profile-types-action-1-chromium-linux.png
  e2e/tests/all-services-view/all-services.spec.ts-snapshots/All-services-view-Profile-type-selector-1-chromium-linux.png
  e2e/tests/diff-flame-graph-view/diff-flame-graph.spec.ts-snapshots/Diff-flame-graph-view-Filters-Adding-a-filter-1-chromium-linux.png
  e2e/tests/diff-flame-graph-view/diff-flame-graph.spec.ts-snapshots/Diff-flame-graph-view-Profile-type-selector-1-chromium-linux.png
  e2e/tests/favorites-view/favorites-view.spec.ts-snapshots/Favorites-view-Layout-switcher-1-chromium-linux.png
  e2e/tests/favorites-view/favorites-view.spec.ts-snapshots/Favorites-view-Main-UI-elements-1-chromium-linux.png
  e2e/tests/favorites-view/favorites-view.spec.ts-snapshots/Favorites-view-Panel-actions-Labels-action-with-group-by-1-chromium-linux.png
  e2e/tests/favorites-view/favorites-view.spec.ts-snapshots/Favorites-view-Panel-actions-Labels-action-without-group-by-1-chromium-linux.png
  e2e/tests/flame-graph-view/flame-graph.spec.ts-snapshots/Flame-graph-view-Panel-actions-Favorite-action-1-chromium-linux.png
  e2e/tests/flame-graph-view/flame-graph.spec.ts-snapshots/Flame-graph-view-Panel-actions-Labels-action-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Filters-Adding-a-filter-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Group-by-labels-selector-Selects-a-label-and-displays-the-breakdown-in-a-new-grid-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Layout-switcher-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Main-UI-elements-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Panel-actions-Expand-panel-action-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Panel-actions-Select-action-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Panel-type-switcher-2-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Profile-type-selector-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Service-selector-1-chromium-linux.png
  e2e/tests/profile-types-view/profile-types.spec.ts-snapshots/Profile-types-view-Layout-switcher-1-chromium-linux.png
  e2e/tests/profile-types-view/profile-types.spec.ts-snapshots/Profile-types-view-Main-UI-elements-1-chromium-linux.png
  e2e/tests/profile-types-view/profile-types.spec.ts-snapshots/Profile-types-view-Panel-actions-Favorite-action-1-chromium-linux.png
  e2e/tests/profile-types-view/profile-types.spec.ts-snapshots/Profile-types-view-Panel-actions-Labels-action-1-chromium-linux.png
  e2e/tests/profile-types-view/profile-types.spec.ts-snapshots/Profile-types-view-Service-selector-1-chromium-linux.png
  e2e/tests/profile-types-view/profile-types.spec.ts-snapshots/Profile-types-view-Settings-button-1-chromium-linux.png
  package.json
  src/plugin.json
  src/shared/infrastructure/tracking/faro/__tests__/faro.spec.ts
  src/shared/ui/PluginInfo.tsx
  yarn.lock
Labels: feat

#290 refactor(Tracking): Better error logging for Scenes variables
  src/pages/ProfilesExplorerView/domain/variables/GroupByVariable/GroupByVariable.tsx
  src/pages/ProfilesExplorerView/domain/variables/ProfileMetricVariable.tsx
  src/pages/ProfilesExplorerView/domain/variables/ServiceNameVariable/ServiceNameVariable.tsx
  src/pages/ProfilesExplorerView/infrastructure/labels/LabelsDataSource.ts
  src/pages/ProfilesExplorerView/infrastructure/series/SeriesDataSource.ts
Labels: refactor

#288 feat(DiffView): Time ranges sync
  e2e/fixtures/pages/PyroscopePage.ts
  e2e/tests/diff-flame-graph-view/diff-flame-graph.spec.ts
  e2e/tests/diff-flame-graph-view/diff-flame-graph.spec.ts-snapshots/Diff-flame-graph-view-Sync-time-ranges-Syncing-flame-graph-range-selection-1-chromium-linux.png
  e2e/tests/diff-flame-graph-view/diff-flame-graph.spec.ts-snapshots/Diff-flame-graph-view-Sync-time-ranges-Syncing-time-picker-range-selection-1-chromium-linux.png
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/SceneExploreDiffFlameGraph.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneComparePanel/SceneComparePanel.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneComparePanel/domain/events/EventEnableSyncTimeRanges.ts
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneComparePanel/domain/events/EventSyncRefresh.ts
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneComparePanel/domain/events/EventSyncTimeRanges.ts
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/ScenePresetsPicker/ScenePresetsPicker.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/domain/types.ts
  src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/components/SceneGroupByLabels/SceneGroupByLabels.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/components/SceneGroupByLabels/components/SceneLabelValuesGrid/components/SceneStatsPanel/SceneStatsPanel.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/components/SceneGroupByLabels/components/SceneLabelValuesGrid/components/SceneStatsPanel/ui/CompareAction.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/components/SceneGroupByLabels/components/SceneLabelValuesGrid/components/SceneStatsPanel/ui/StatsPanel.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/components/SceneGroupByLabels/domain/events/EventSelectForCompare.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/components/SceneGroupByLabels/ui/CompareControls.tsx
  src/shared/components/FlameGraph/components/domain/getExportFilename.ts
  src/shared/ui/PluginInfo.tsx
Labels: feat

#291 fix(SceneComparePanel): Temporarily disable time range sync
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneComparePanel/SceneComparePanel.tsx
  src/shared/components/SceneTimePickerWithoutSync/SceneTimePickerWithoutSync.tsx
Labels: fix

#289 chore(Versioning): Bump the minor version by default
  .github/workflows/create-new-version.yml
  scripts/create_version_tag
Labels: chore

#300 feat(Timeseries): Add open in Explore menu item
  src/pages/ProfilesExplorerView/components/SceneLabelValuesTimeseries.tsx
  src/pages/ProfilesExplorerView/helpers/__tests__/getExploreUrl.spec.ts
  src/pages/ProfilesExplorerView/helpers/getExploreUrl.ts
  src/shared/domain/reportInteraction.ts
Labels: feat

#302 test(EndToEnd): Add expectation to prevent waiting when a fatal error…
  e2e/fixtures/pages/PyroscopePage.ts
Labels: test

#298 ci: Prepare for GitHub Actions migration
  .drone.migration.jsonnet
  drone_migration.yaml
Labels: ci

#303 refactor: prepare Investigations support
  src/pages/ProfilesExplorerView/components/SceneLabelValuesTimeseries.tsx
  src/pages/ProfilesExplorerView/infrastructure/timeseries/buildTimeSeriesQueryRunner.ts
  src/shared/domain/reportInteraction.ts
Labels: refactor
