Repository grafana/profiles-drilldown, pull requests merged in 2024-08, with the labels that each got.

#4 test(EndToEnd): Switch to latest Pyroscope Docker image
  Dockerfile.pyroscope.e2e
  e2e/tests/comparison-diff-view/comparison-diff-view.spec.ts-snapshots/Mouse-selections-of-time-ranges-on-the-timelin-4a595--on-the-main-baseline-comparison-timelines-6-chromium-linux.png
  e2e/tests/comparison-diff-view/comparison-diff-view.spec.ts-snapshots/Mouse-selections-of-time-ranges-on-the-timelin-6c1db--on-the-main-baseline-comparison-timelines-2-chromium-linux.png
  e2e/tests/comparison-diff-view/comparison-diff-view.spec.ts-snapshots/Mouse-selections-of-time-ranges-on-the-timelin-71c7a--on-the-main-baseline-comparison-timelines-9-chromium-linux.png
  e2e/tests/comparison-diff-view/comparison-diff-view.spec.ts-snapshots/Mouse-selections-of-time-ranges-on-the-timelin-a8a53--on-the-main-baseline-comparison-timelines-3-chromium-linux.png
  e2e/tests/comparison-diff-view/comparison-diff-view.spec.ts-snapshots/Mouse-selections-of-time-ranges-on-the-timelin-abad3--on-the-main-baseline-comparison-timelines-5-chromium-linux.png
  e2e/tests/comparison-diff-view/comparison-diff-view.spec.ts-snapshots/Mouse-selections-of-time-ranges-on-the-timelin-c2c66-on-the-main-baseline-comparison-timelines-10-chromium-linux.png
  e2e/tests/comparison-diff-view/comparison-diff-view.spec.ts-snapshots/Query-builders-Can-add-a-single-filter-in-the-baseline-panel-3-chromium-linux.png
  e2e/tests/comparison-diff-view/comparison-diff-view.spec.ts-snapshots/Query-builders-Can-add-a-single-filter-in-the-comparison-panel-2-chromium-linux.png
  e2e/tests/comparison-diff-view/comparison-diff-view.spec.ts-snapshots/Time-picker-Moving-backwards-2-chromium-linux.png
  e2e/tests/comparison-diff-view/comparison-diff-view.spec.ts-snapshots/Time-picker-Moving-backwards-3-chromium-linux.png
  e2e/tests/comparison-diff-view/comparison-diff-view.spec.ts-snapshots/Time-picker-Moving-forwards-2-chromium-linux.png
  e2e/tests/comparison-diff-view/comparison-diff-view.spec.ts-snapshots/Time-picker-Moving-forwards-3-chromium-linux.png
  e2e/tests/comparison-diff-view/comparison-diff-view.spec.ts-snapshots/Time-picker-Zooming-out-2-chromium-linux.png
  e2e/tests/comparison-diff-view/comparison-diff-view.spec.ts-snapshots/Time-picker-Zooming-out-3-chromium-linux.png
  e2e/tests/comparison-diff-view/comparison-diff-view.spec.ts-snapshots/Toolbar-Profile-type-selection-Updates-the-toolbar-and-the-panels-data-go---inuse-space-2-chromium-linux.png
  e2e/tests/comparison-diff-view/comparison-diff-view.spec.ts-snapshots/Toolbar-Profile-type-selection-Updates-the-toolbar-and-the-panels-data-go---inuse-space-3-chromium-linux.png
  e2e/tests/comparison-diff-view/comparison-diff-view.spec.ts-snapshots/Toolbar-Service-selection-Updates-the-toolbar-and-the-panels-data-load-generator-2-chromium-linux.png
  e2e/tests/comparison-diff-view/comparison-diff-view.spec.ts-snapshots/Toolbar-Service-selection-Updates-the-toolbar-and-the-panels-data-load-generator-3-chromium-linux.png
  e2e/tests/comparison-view/comparison-view.spec.ts-snapshots/Mouse-selections-of-time-ranges-on-the-timelin-71c7a--on-the-main-baseline-comparison-timelines-9-chromium-linux.png
  e2e/tests/comparison-view/comparison-view.spec.ts-snapshots/Mouse-selections-of-time-ranges-on-the-timelin-c2c66-on-the-main-baseline-comparison-timelines-10-chromium-linux.png
  e2e/tests/comparison-view/comparison-view.spec.ts-snapshots/Toolbar-Profile-type-selection-Updates-the-toolbar-and-the-panels-data-go---inuse-space-2-chromium-linux.png
  e2e/tests/comparison-view/comparison-view.spec.ts-snapshots/Toolbar-Profile-type-selection-Updates-the-toolbar-and-the-panels-data-go---inuse-space-3-chromium-linux.png
  src/shared/components/QueryAnalysisTooltip/QueryAnalysisTooltip.tsx
  src/shared/components/QueryAnalysisTooltip/domain/useQueryAnalysis.ts
  src/shared/ui/PageTitle.tsx
Labels: test

#108 feat(Timeseries): Add total resource consumption in legend
  src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/infrastructure/data-transformations.ts
  src/pages/ProfilesExplorerView/components/SceneLabelValueStat.tsx
  src/pages/ProfilesExplorerView/components/SceneLabelValuesBarGauge.tsx
  src/pages/ProfilesExplorerView/components/SceneLabelValuesTimeseries.tsx
  src/pages/ProfilesExplorerView/components/SceneMainServiceTimeseries.tsx
Labels: feat

#111 fix(Ci): Fix docker compose commands
  .config/README.md
  package.json
Labels: fix

#110 fix(Labels): Fix "Discarded by user" error in the UI
  src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/components/SceneErrorState/SceneErrorState.tsx
  src/pages/ProfilesExplorerView/domain/variables/FiltersVariable/FiltersVariable.tsx
  src/pages/ProfilesExplorerView/domain/variables/GroupByVariable/GroupByVariable.tsx
  src/pages/ProfilesExplorerView/infrastructure/labels/LabelsDataSource.ts
  src/shared/components/QueryBuilder/QueryBuilder.tsx
  src/shared/components/QueryBuilder/domain/actions.ts
  src/shared/components/QueryBuilder/domain/helpers/__tests__/filtersToQuery.spec.ts
  src/shared/components/QueryBuilder/domain/helpers/__tests__/queryToFilters.spec.ts
  src/shared/components/QueryBuilder/domain/helpers/filtersToQuery.ts
  src/shared/components/QueryBuilder/domain/helpers/queryToFilters.ts
  src/shared/components/QueryBuilder/domain/stateMachine.ts
  src/shared/components/QueryBuilder/domain/types.ts
  src/shared/components/QueryBuilder/domain/useStateMachine.tsx
Labels: fix

#113 chore(E2E): Upgrade Playwright to v1.46.0
  Dockerfile.plugin.e2e
  package.json
  yarn.lock
Labels: chore

#114 docs: Add link to Explore Traces
  docs/sources/get-started/index.md
Labels: type/docs

#118 docs: Fix link to Explore Traces
  docs/sources/get-started/index.md
Labels: type/docs

#120 refactor(*): Prepare comparison flow improvements
  src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/SceneByVariableRepeaterGrid.tsx
  src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/components/SceneLayoutSwitcher.tsx
  src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/components/ScenePanelTypeSwitcher.tsx
  src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/components/SceneQuickFilter.tsx
  src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/domain/sortFavGridItems.ts
  src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/infrastructure/data-transformations.ts
  src/pages/ProfilesExplorerView/components/SceneExploreAllServices/SceneExploreAllServices.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreFavorites/SceneExploreFavorites.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/SceneExploreServiceFlameGraph.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/SceneFlameGraph.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/SceneExploreServiceLabels.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/components/SceneGroupByLabels.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/components/SceneLabelValuesGrid.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceProfileTypes/SceneExploreServiceProfileTypes.tsx
  src/pages/ProfilesExplorerView/components/SceneLabelValuesBarGauge.tsx
  src/pages/ProfilesExplorerView/components/SceneLabelValuesTimeseries.tsx
  src/pages/ProfilesExplorerView/components/SceneMainServiceTimeseries.tsx
  src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/SceneProfilesExplorer.tsx
  src/pages/ProfilesExplorerView/domain/actions/CompareAction.tsx
  src/pages/ProfilesExplorerView/domain/events/EventDataReceived.ts
  src/pages/ProfilesExplorerView/domain/variables/FiltersVariable/FiltersVariable.tsx
  src/pages/ProfilesExplorerView/domain/variables/GroupByVariable/GroupBySelector.tsx
  src/pages/ProfilesExplorerView/domain/variables/GroupByVariable/GroupByVariable.tsx
  src/pages/ProfilesExplorerView/domain/variables/ProfileMetricVariable.tsx
  src/pages/ProfilesExplorerView/domain/variables/ProfilesDataSourceVariable.ts
  src/pages/ProfilesExplorerView/domain/variables/ServiceNameVariable.tsx
  src/pages/ProfilesExplorerView/helpers/findSceneObjectByClass.ts
  src/pages/ProfilesExplorerView/helpers/findSceneObjectByKey.ts
  src/pages/ProfilesExplorerView/infrastructure/helpers/getSeriesLabelFieldName.ts
  src/pages/ProfilesExplorerView/infrastructure/helpers/getSeriesStatsValue.ts
  src/pages/ProfilesExplorerView/infrastructure/labels/LabelsDataSource.ts
  src/shared/infrastructure/labels/labelsRepository.ts
Labels: refactor

#123 fix(SceneLabelValuePanel): Fix border color when baseline/comparison is selected
  src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/components/SceneGroupByLabels/components/SceneLabelValuesGrid/components/SceneLabelValuePanel.tsx
Labels: fix

#124 fix(ScenesProfileExplorer): Make labels more responsive on smaller screens
  src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/SceneProfilesExplorer.tsx
  src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/ui/ExplorationTypeSelector.tsx
Labels: fix

#119 feat(CompareView): Implement new Comparison view with Scenes
  e2e/tests/explore-profiles/explore-profiles.spec.ts
  src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/SceneByVariableRepeaterGrid.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/SceneExploreDiffFlameGraph.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneComparePanel/SceneComparePanel.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneComparePanel/components/SceneTimeRangeWithAnnotations.ts
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneComparePanel/domain/RangeAnnotation.ts
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneComparePanel/domain/actions/SwitchTimeRangeSelectionModeAction.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneComparePanel/domain/evaluateTimeRange.ts
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneComparePanel/domain/events/EventSwitchTimerangeSelectionMode.ts
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneComparePanel/domain/parseUrlParam.ts
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneComparePanel/infrastructure/buildCompareTimeSeriesQueryRunner.ts
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneDiffFlameGraph/SceneDiffFlameGraph.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneDiffFlameGraph/infrastructure/DiffProfileApiClient.ts
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneDiffFlameGraph/infrastructure/useFetchDiffProfile.ts
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/domain/behaviours/syncYAxis.ts
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/SceneFlameGraph.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/components/SceneGroupByLabels/SceneGroupByLabels.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/components/SceneGroupByLabels/components/SceneLabelValuesGrid/SceneLabelValuesGrid.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/components/SceneGroupByLabels/components/SceneLabelValuesGrid/components/SceneLabelValuePanel.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/components/SceneGroupByLabels/components/SceneLabelValuesGrid/components/SceneStatsPanel/SceneStatsPanel.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/components/SceneGroupByLabels/components/SceneLabelValuesGrid/components/SceneStatsPanel/ui/CompareAction.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/components/SceneGroupByLabels/components/SceneLabelValuesGrid/components/SceneStatsPanel/ui/StatsPanel.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/components/SceneGroupByLabels/ui/CompareActions.tsx
  src/pages/ProfilesExplorerView/components/SceneLabelValuesBarGauge.tsx
  src/pages/ProfilesExplorerView/components/SceneLabelValuesTimeseries.tsx
  src/pages/ProfilesExplorerView/components/SceneMainServiceTimeseries.tsx
  src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/SceneProfilesExplorer.tsx
  src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/ui/ExplorationTypeSelector.tsx
  src/pages/ProfilesExplorerView/domain/events/EventDataReceived.ts
  src/pages/ProfilesExplorerView/domain/events/EventTimeseriesDataReceived.ts
  src/pages/ProfilesExplorerView/domain/events/EventViewDiffFlameGraph.tsx
  src/pages/ProfilesExplorerView/domain/getDefaultTimeRange.ts
  src/pages/ProfilesExplorerView/domain/useBuildPyroscopeQuery.ts
  src/pages/ProfilesExplorerView/domain/variables/FiltersVariable/FiltersVariable.tsx
  src/pages/ProfilesExplorerView/domain/variables/FiltersVariable/filters-ops.tsx
  src/pages/ProfilesExplorerView/domain/variables/ServiceNameVariable.tsx
  src/plugin.json
  src/shared/ui/PageTitle.tsx
Labels: feat

#130 docs(Ai): Add missing AI integration info
  .env.local
  docs/CONTRIBUTING.md
Labels: type/docs

#129 fix(DiffFlameGraph): Fix the "Explain Flame Graph" (AI) feature
  src/pages/ProfilesExplorerView/components/SceneAiPanel/SceneAiPanel.tsx
  src/pages/ProfilesExplorerView/components/SceneAiPanel/components/AiButton/AIButton.tsx
  src/pages/ProfilesExplorerView/components/SceneAiPanel/components/AiButton/infrastructure/useFetchLlmPluginStatus.ts
  src/pages/ProfilesExplorerView/components/SceneAiPanel/components/AiReply.tsx
  src/pages/ProfilesExplorerView/components/SceneAiPanel/components/FollowUpForm.tsx
  src/pages/ProfilesExplorerView/components/SceneAiPanel/domain/buildLlmPrompts.ts
  src/pages/ProfilesExplorerView/components/SceneAiPanel/domain/useOpenAiChatCompletions.ts
  src/pages/ProfilesExplorerView/components/SceneAiPanel/infrastructure/ProfileApiClient.ts
  src/pages/ProfilesExplorerView/components/SceneAiPanel/infrastructure/cleanupDotResponse.ts
  src/pages/ProfilesExplorerView/components/SceneAiPanel/infrastructure/useFetchDotProfiles.ts
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/SceneExploreDiffFlameGraph.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneDiffFlameGraph/SceneDiffFlameGraph.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneDiffFlameGraph/infrastructure/useFetchDiffProfile.ts
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/SceneFlameGraph.tsx
  src/pages/ProfilesExplorerView/domain/variables/FiltersVariable/FiltersVariable.tsx
  src/shared/domain/useToggleSidePanel.ts
Labels: fix

#132 feat(FlameGraph): Add missing export menu
  .prettierignore
  src/pages/ProfilesExplorerView/components/SceneAiPanel/infrastructure/useFetchDotProfiles.ts
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/SceneFlameGraph.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneExportMenu.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/domain/__tests__/getExportFilename.spec.ts
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/domain/getExportFilename.ts
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/infrastructure/PprofApiClient.ts
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/infrastructure/PprofRequest.ts
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/infrastructure/flamegraphDotComApiClient.ts
  src/pages/ProfilesExplorerView/infrastructure/profiles/ProfileApiClient.ts
  src/shared/components/FlameGraph/components/ExportMenu.tsx
  src/shared/components/FlameGraph/components/domain/useExportMenu.ts
  src/shared/components/FlameGraph/components/infrastructure/PprofRequestWithoutMaxNodes.ts
  src/shared/components/FlameGraph/components/infrastructure/pprofApiClient.ts
Labels: feat

#134 test(EndToEnd): Add "All services" tests
  e2e/README.md
  e2e/config/constants.ts
  e2e/fixtures/pages/ExploreProfilesPage.ts
  e2e/fixtures/pages/PyroscopePage.ts
  e2e/tests/all-services-view/all-services.spec.ts
  e2e/tests/all-services-view/all-services.spec.ts-snapshots/All-services-view-Layout-switcher-1-chromium-linux.png
  e2e/tests/all-services-view/all-services.spec.ts-snapshots/All-services-view-Main-UI-elements-1-chromium-linux.png
  e2e/tests/all-services-view/all-services.spec.ts-snapshots/All-services-view-Panel-actions-Favorite-action-1-chromium-linux.png
  e2e/tests/all-services-view/all-services.spec.ts-snapshots/All-services-view-Panel-actions-Flame-graph-action-1-chromium-linux.png
  e2e/tests/all-services-view/all-services.spec.ts-snapshots/All-services-view-Panel-actions-Labels-action-1-chromium-linux.png
  e2e/tests/all-services-view/all-services.spec.ts-snapshots/All-services-view-Panel-actions-Profile-types-action-1-chromium-linux.png
  e2e/tests/all-services-view/all-services.spec.ts-snapshots/All-services-view-Profile-type-selector-1-chromium-linux.png
  e2e/tests/all-services-view/hide-all-controls.css
  e2e/tests/explore-profiles/explore-profiles.spec.ts
  samples/provisioning-local/datasources/datasources.yaml
  samples/provisioning-remote/datasources/datasources.yaml
  samples/provisioning/datasources/datasources.yaml
  src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/SceneByVariableRepeaterGrid.tsx
  src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/components/SceneLayoutSwitcher.tsx
  src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/components/SceneQuickFilter.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/components/SceneGroupByLabels/components/SceneLabelValuesGrid/SceneLabelValuesGrid.tsx
  src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/SceneProfilesExplorer.tsx
  src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/ui/ExplorationTypeSelector.tsx
  src/pages/ProfilesExplorerView/domain/actions/SelectAction.tsx
Labels: test

#138 build(PrValidationTitle): Add "build" task type
  .github/workflows/pr-validation.yml
Labels: build

#140 feat(DiffFlameGraph): Add flame graph range in timeseries legend
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneComparePanel/SceneComparePanel.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneComparePanel/components/SceneTimeRangeWithAnnotations.ts
  src/pages/ProfilesExplorerView/components/SceneLabelValuesTimeseries.tsx
Labels: feat

#141 feat(*): Add histogram visualizations
  src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/SceneByVariableRepeaterGrid.tsx
  src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/components/ScenePanelTypeSwitcher.tsx
  src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/types/GridItemData.ts
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneComparePanel/SceneComparePanel.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreFavorites/SceneExploreFavorites.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/components/SceneGroupByLabels/SceneGroupByLabels.tsx
  src/pages/ProfilesExplorerView/components/SceneLabelValuesHistogram.tsx
  src/pages/ProfilesExplorerView/components/SceneLabelValuesTimeseries.tsx
  src/pages/ProfilesExplorerView/helpers/panelBuilder.ts
Labels: feat

#136 test(EndToEnd): Add "Flame graph" tests
  e2e/config/constants.ts
  e2e/fixtures/css/hide-all-controls.css
  e2e/fixtures/pages/ExploreProfilesPage.ts
  e2e/fixtures/pages/PyroscopePage.ts
  e2e/fixtures/pages/SettingsPage.ts
  e2e/tests/all-services-view/all-services.spec.ts
  e2e/tests/comparison-diff-view/comparison-diff-view.spec.ts
  e2e/tests/comparison-view/comparison-view-query-analysis.spec.ts
  e2e/tests/comparison-view/comparison-view.spec.ts
  e2e/tests/flame-graph-view/fixtures/SelectMergeProfile.json
  e2e/tests/flame-graph-view/flame-graph.spec.ts
  e2e/tests/flame-graph-view/flame-graph.spec.ts-snapshots/Flame-graph-view-Filters-Adding-a-filter-1-chromium-linux.png
  e2e/tests/flame-graph-view/flame-graph.spec.ts-snapshots/Flame-graph-view-Main-UI-elements-1-chromium-linux.png
  e2e/tests/flame-graph-view/flame-graph.spec.ts-snapshots/Flame-graph-view-Panel-actions-Favorite-action-1-chromium-linux.png
  e2e/tests/flame-graph-view/flame-graph.spec.ts-snapshots/Flame-graph-view-Panel-actions-Labels-action-1-chromium-linux.png
  e2e/tests/flame-graph-view/flame-graph.spec.ts-snapshots/Flame-graph-view-Profile-type-selector-1-chromium-linux.png
  e2e/tests/flame-graph-view/flame-graph.spec.ts-snapshots/Flame-graph-view-Service-selector-1-chromium-linux.png
  e2e/tests/flame-graph-view/github-integration.spec.ts
  e2e/tests/onboarding-view/onboarding.spec.ts
  e2e/tests/onboarding-view/onboarding.spec.ts-snapshots/Onboarding-displays-an-onboarding-modal-that-can-be-closed-1-chromium-linux.png
  e2e/tests/onboarding-view/onboarding.spec.ts-snapshots/Onboarding-displays-an-onboarding-modal-that-can-be-closed-2-chromium-linux.png
  e2e/tests/onboarding-view/onboarding.spec.ts-snapshots/Onboarding-displays-an-onboarding-modal-that-can-be-closed-3-chromium-linux.png
  e2e/tests/profile-types-view/profile-types.spec.ts
  e2e/tests/settings-view.spec.ts
  e2e/tests/settings-view.spec.ts-snapshots/Plugin-Settings-Flame-graph-settings-Can-be-modified-1-chromium-linux.png
  e2e/tests/settings-view/settings-view.spec.ts
  e2e/tests/settings-view/settings-view.spec.ts-snapshots/Plugin-Settings-Flame-graph-settings-Can-be-modified-for-the-Flame-graph-views-1-chromium-linux.png
  e2e/tests/settings-view/settings-view.spec.ts-snapshots/Plugin-Settings-Flame-graph-settings-Can-be-modified-for-the-Flame-graph-views-2-chromium-linux.png
  src/pages/ComparisonView/components/ComparisonDiffPanel/ComparisonDiffPanel.tsx
  src/shared/components/AiPanel/components/AIButton.tsx
  src/shared/components/QueryBuilder/ui/chiclets/ChicletAttributeOperator.tsx
  src/shared/components/QueryBuilder/ui/chiclets/ChicletAttributeOperatorValue.tsx
  src/shared/components/QueryBuilder/ui/chiclets/ChicletsList.tsx
  src/shared/components/QueryBuilder/ui/chiclets/PartialChiclet.tsx
Labels: test

#144 test(Favorites): Add E2E tests
  e2e/fixtures/pages/ExploreProfilesPage.ts
  e2e/tests/all-services-view/all-services.spec.ts
  e2e/tests/favorites-view/favorites-view.spec.ts
  e2e/tests/favorites-view/favorites-view.spec.ts-snapshots/Favorites-view-Layout-switcher-1-chromium-linux.png
  e2e/tests/favorites-view/favorites-view.spec.ts-snapshots/Favorites-view-Main-UI-elements-1-chromium-linux.png
  e2e/tests/favorites-view/favorites-view.spec.ts-snapshots/Favorites-view-Panel-actions-Expand-panel-action-1-chromium-linux.png
  e2e/tests/favorites-view/favorites-view.spec.ts-snapshots/Favorites-view-Panel-actions-Flame-graph-action-1-chromium-linux.png
  e2e/tests/favorites-view/favorites-view.spec.ts-snapshots/Favorites-view-Panel-actions-Labels-action-with-group-by-1-chromium-linux.png
  e2e/tests/favorites-view/favorites-view.spec.ts-snapshots/Favorites-view-Panel-actions-Labels-action-without-group-by-1-chromium-linux.png
  e2e/tests/flame-graph-view/github-integration.spec.ts
  e2e/tests/profile-types-view/profile-types.spec.ts
  src/pages/ProfilesExplorerView/domain/actions/SelectAction.tsx
Labels: test

#128 feat: create new browser history entry on some user actions
  src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/components/SceneGroupByLabels/SceneGroupByLabels.tsx
  src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/SceneProfilesExplorer.tsx
  src/pages/ProfilesExplorerView/domain/variables/GroupByVariable/GroupByVariable.tsx
  src/pages/ProfilesExplorerView/domain/variables/ProfileMetricVariable.tsx
  src/pages/ProfilesExplorerView/domain/variables/ServiceNameVariable.tsx
  src/shared/domain/history.ts
  src/shared/domain/url-params/useUrlSearchParams.ts
Labels: feat

#145 chore: fix version and changelog for 0.1.7
  CHANGELOG.md
  package.json
Labels: chore

#146 test(EndToEnd): Labels tests
  e2e/fixtures/pages/ExploreProfilesPage.ts
  e2e/fixtures/pages/PyroscopePage.ts
  e2e/tests/all-services-view/all-services.spec.ts
  e2e/tests/favorites-view/favorites-view.spec.ts
  e2e/tests/labels-view/labels.spec.ts
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Filters-Adding-a-filter-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Group-by-labels-selector-After-sel-dbe5f-n-items-then-clicking-on-the-Compare-button-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Group-by-labels-selector-After-sel-f81f2-on-item-then-clicking-on-the-Compare-button-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Group-by-labels-selector-After-selecting-a-label-Panel-actions-Add-to-filters-action-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Group-by-labels-selector-After-selecting-a-label-Panel-actions-Flame-graph-action-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Group-by-labels-selector-Selects-a-label-and-displays-the-breakdown-in-a-new-grid-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Layout-switcher-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Main-UI-elements-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Panel-actions-Expand-panel-action-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Panel-actions-Select-action-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Panel-type-switcher-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Panel-type-switcher-2-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Profile-type-selector-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Service-selector-1-chromium-linux.png
  e2e/tests/settings-view/settings-view.spec.ts
  e2e/tests/settings-view/settings-view.spec.ts-snapshots/Plugin-Settings-Flame-graph-settings-Can-be-modified-for-the-Flame-graph-views-1-chromium-linux.png
  e2e/tests/settings-view/settings-view.spec.ts-snapshots/Plugin-Settings-Flame-graph-settings-Can-be-modified-for-the-Flame-graph-views-2-chromium-linux.png
  src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/components/SceneNoDataSwitcher.tsx
  src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/components/ScenePanelTypeSwitcher.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneDiffFlameGraph/SceneDiffFlameGraph.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/SceneFlameGraph.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/components/SceneGroupByLabels/SceneGroupByLabels.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/components/SceneGroupByLabels/components/SceneLabelValuesGrid/components/SceneStatsPanel/ui/StatsPanel.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/components/SceneGroupByLabels/ui/CompareControls.tsx
  src/pages/ProfilesExplorerView/domain/variables/GroupByVariable/GroupBySelector.tsx
Labels: test
