Repository grafana/profiles-drilldown, pull requests merged in 2024-07, with the labels that each got.

#51 docs: Update contribution guidelines
  docs/CODE-ARCHITECTURE.md
  docs/CONTRIBUTING.md
Labels: docs

#50 ci: Build CHANGELOG
  .github/workflows/create-new-version.yml
  CHANGELOG.md
  package.json
  yarn.lock
Labels: ci

#52 docs: Configure custom PR label
  .github/workflows/pr-validation.yml
Labels: type/docs

#58 fix(CompareAction): Add missing data source query parameter to compare URL
  src/pages/ProfilesExplorerView/actions/CompareAction.tsx
Labels: fix

#56 docs: Update README.md
  README.md
Labels: type/docs, docs

#57 docs: Update CONTRIBUTING.md
  docs/CONTRIBUTING.md
Labels: type/docs, docs

#60 feat(DataSource): Persist the last selected data source
  src/pages/ProfilesExplorerView/variables/ProfilesDataSourceVariable.ts
  src/shared/infrastructure/http/ApiClient.ts
  src/shared/infrastructure/http/__tests__/ApiClient.spec.ts
Labels: feat

#25 fix(FunctionDetails): Get timeline state from Flame Graph component
  src/pages/ProfilesExplorerView/components/SceneMainServiceTimeseries.tsx
  src/pages/ProfilesExplorerView/exploration-types/SceneServiceFlameGraph/SceneFlameGraph.tsx
  src/shared/components/FunctionDetailsPanel/infrastructure/useFetchFunctionsDetails.ts
Labels: fix

#64 feat(Analytics): Track Explore Profiles user actions
  src/pages/ProfilesExplorerView/SceneProfilesExplorer.tsx
  src/pages/ProfilesExplorerView/actions/CompareAction.tsx
  src/pages/ProfilesExplorerView/actions/FavAction.tsx
  src/pages/ProfilesExplorerView/actions/SelectAction.tsx
  src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/SceneLayoutSwitcher.tsx
  src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/SceneNoDataSwitcher.tsx
  src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/SceneQuickFilter.tsx
  src/pages/ProfilesExplorerView/variables/GroupByVariable/GroupByVariable.tsx
  src/pages/ProfilesExplorerView/variables/ProfileMetricVariable.tsx
  src/pages/ProfilesExplorerView/variables/ServiceNameVariable.tsx
  src/shared/domain/reportInteraction.ts
Labels: feat

#65 feat: Update plugin metadata to auto enable
  src/plugin.json
Labels: feat

#67 chore: improve onboarding flow for OSS users
  e2e/tests/onboarding.spec.ts
  e2e/tests/onboarding.spec.ts-snapshots/Onboarding-displays-an-onboarding-modal-that-can-be-closed-3-chromium-linux.png
  e2e/tests/onboarding.spec.ts-snapshots/Onboarding-displays-an-onboarding-modal-that-can-be-closed-4-chromium-linux.png
  src/README.md
  src/app/components/Onboarding/domain/useOnboarding.tsx
  src/app/components/Onboarding/domain/useOnboardingModal.tsx
  src/app/components/Onboarding/ui/OnboardingModal.tsx
  src/img/hero-image-explore-profiles.png
  src/img/resolve-incidents.png
  src/plugin.json
  src/shared/components/FunctionDetailsPanel/infrastructure/useFetchFunctionsDetails.ts
  src/shared/infrastructure/http/ApiClient.ts
Labels: chore

#68 chore: ci fix
  .github/workflows/create-new-version.yml
Labels: chore

#70 fix(Header): Switch the exploration type radio button group to a select on narrow screens
  src/pages/ProfilesExplorerView/ProfilesExplorerView.tsx
  src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/SceneQuickFilter.tsx
  src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/SceneProfilesExplorer.tsx
  src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/ui/ExplorationTypeSelector.tsx
  src/pages/ProfilesExplorerView/exploration-types/SceneExploreServiceLabels/SceneGroupByLabels.tsx
Labels: fix

#71 chore: enable -latest update on release
  .drone.jsonnet
Labels: chore

#59 docs: Add validation Github Action for docs PRs
  .github/workflows/ci.yml
  .github/workflows/is-compatible.yml
  .github/workflows/publish-technical-documentation-next.yml
  .github/workflows/validate-documentation.yml
  .prettierignore
  README.md
  docs/CONTRIBUTING.md
  docs/sources/_index.md
  docs/sources/access/index.md
  docs/sources/concepts/index.md
  docs/sources/determine-use-case/index.md
  docs/sources/get-started/index.md
  docs/sources/investigate/index.md
  package.json
Labels: type/docs

#72 feat(LabelsExploration): Introduce bar gauge visualisations
  .github/workflows/ci.yml
  src/pages/ProfilesExplorerView/actions/FavAction.tsx
  src/pages/ProfilesExplorerView/actions/SelectAction.tsx
  src/pages/ProfilesExplorerView/components/SceneAllLabelValuesTable.tsx
  src/pages/ProfilesExplorerView/components/SceneAllLabelValuesTimeseries.tsx
  src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/GridItemData.ts
  src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/SceneByVariableRepeaterGrid.tsx
  src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/ScenePanelTypeSwitcher.tsx
  src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/infrastructure/data-transformations.ts
  src/pages/ProfilesExplorerView/components/SceneLabelValuesBarGauge.tsx
  src/pages/ProfilesExplorerView/components/SceneLabelValuesTimeseries.tsx
  src/pages/ProfilesExplorerView/components/SceneMainServiceTimeseries.tsx
  src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/SceneProfilesExplorer.tsx
  src/pages/ProfilesExplorerView/data/favorites/FavoritesDataSource.ts
  src/pages/ProfilesExplorerView/events/EventViewLabelValuesDistribution.tsx
  src/pages/ProfilesExplorerView/exploration-types/SceneExploreFavorites/SceneExploreFavorites.tsx
  src/pages/ProfilesExplorerView/exploration-types/SceneExploreServiceLabels/SceneGroupByLabels.tsx
Labels: feat

#77 ci: Fix CI GitHub action execution
  .github/workflows/ci.yml
Labels: ci

#78 fix(PanelTitle): Remove series count when only 1 serie
  src/pages/ProfilesExplorerView/components/SceneLabelValuesBarGauge.tsx
  src/pages/ProfilesExplorerView/components/SceneLabelValuesTimeseries.tsx
Labels: fix

#80 feat(*): Avoid no data panels
  src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/SceneByVariableRepeaterGrid.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreAllServices/SceneExploreAllServices.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreFavorites/SceneExploreFavorites.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/SceneExploreServiceFlameGraph.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/SceneFlameGraph.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/SceneGroupByLabels.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceProfileTypes/SceneExploreServiceProfileTypes.tsx
  src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/SceneProfilesExplorer.tsx
  src/pages/ProfilesExplorerView/domain/variables/ProfileMetricVariable.tsx
  src/pages/ProfilesExplorerView/domain/variables/ServiceNameVariable.tsx
  src/pages/ProfilesExplorerView/infrastructure/series/SeriesDataSource.ts
  src/pages/ProfilesExplorerView/infrastructure/series/formatSeriesToProfileMetrics.ts
  src/pages/ProfilesExplorerView/infrastructure/series/formatSeriesToServices.ts
  src/pages/ProfilesExplorerView/infrastructure/series/http/SeriesApiClient.ts
  src/pages/ProfilesExplorerView/infrastructure/series/http/formatSeriesResponse.ts
  src/pages/ProfilesExplorerView/infrastructure/series/http/seriesRepository.ts
  src/shared/infrastructure/services/servicesApiClient.ts
Labels: feat

#85 fix(SceneLabelValuesTimeseries): Colors and legends are preserved on expanded timeseries
  src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/infrastructure/data-transformations.ts
  src/pages/ProfilesExplorerView/components/SceneLabelValuesTimeseries.tsx
Labels: fix

#82 refactor(*): Improve scene objects cohesion
  src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/components/ScenePanelTypeSwitcher.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreAllServices/SceneExploreAllServices.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreFavorites/SceneExploreFavorites.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/SceneExploreServiceFlameGraph.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/SceneExploreServiceLabels.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/SceneGroupByLabels.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceProfileTypes/SceneExploreServiceProfileTypes.tsx
  src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/SceneProfilesExplorer.tsx
  src/pages/ProfilesExplorerView/domain/variables/ProfileMetricVariable.tsx
  src/pages/ProfilesExplorerView/domain/variables/ServiceNameVariable.tsx
  src/pages/ProfilesExplorerView/infrastructure/series/SeriesDataSource.ts
  src/pages/ProfilesExplorerView/infrastructure/timeseries/buildTimeSeriesQueryRunner.ts
Labels: refactor

#86 fix(SceneByVariableRepeaterGrid): Prevent extra renders
  src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/SceneByVariableRepeaterGrid.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/SceneGroupByLabels.tsx
  src/pages/ProfilesExplorerView/infrastructure/labels/LabelsDataSource.ts
Labels: fix

#89 chore: Maintenance
  .github/workflows/ci.yml
  .github/workflows/create-new-version.yml
  .github/workflows/is-compatible.yml
  package.json
  yarn.lock
Labels: chore

#87 docs: Fix missing image and heading level
  docs/sources/determine-use-case/index.md
  docs/sources/get-started/index.md
Labels: type/docs

#90 chore: Maintenance
  .github/workflows/create-new-version.yml
Labels: chore

#93 feat(Labels): Various UI/UX improvements
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/SceneByVariableRepeaterGrid.tsx
  src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/components/ScenePanelTypeSwitcher.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/SceneGroupByLabels.tsx
  src/pages/ProfilesExplorerView/components/SceneLabelValueStat.tsx
  src/pages/ProfilesExplorerView/components/SceneLabelValuesBarGauge.tsx
  src/pages/ProfilesExplorerView/components/SceneLabelValuesTimeseries.tsx
Labels: feat

#96 ci(GitHubActions): Use Databases Frontend CI Bot email
  .github/workflows/create-new-version.yml
Labels: ci

#91 docs: Add blog post link and video
  docs/sources/get-started/index.md
  docs/sources/investigate/index.md
Labels: type/docs

#94 feat(*): Revamp exploration type selector
  .github/ISSUE_TEMPLATE/bug_report.md
  e2e/fixtures/pages/ExploreProfilesPage.ts
  src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/SceneProfilesExplorer.tsx
  src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/ui/ExplorationTypeSelector.tsx
Labels: feat

#101 fix(Favorites): Render "No results" when there are no favorites
  src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/SceneByVariableRepeaterGrid.tsx
Labels: fix

#102 refactor(Labels): Move some "groupBy" logic out of SceneByVariableRepeaterGrid
  src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/SceneByVariableRepeaterGrid.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/SceneGroupByLabels.tsx
  src/pages/ProfilesExplorerView/components/SceneLabelValuesTimeseries.tsx
  src/pages/ProfilesExplorerView/domain/variables/ProfileMetricVariable.tsx
Labels: refactor

#103 chore(App): Remove redirections to legacy pages
  src/app/App.tsx
Labels: chore

#107 docs: Change doc visibility
  docs/sources/_index.md
Labels: type/docs
