Repository grafana/profiles-drilldown, pull requests merged in 2024-09, with the labels that each got.

#147 feat: support submodules for GitHub Integration
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneFunctionDetailsPanel/components/CodeContainer/domain/useCodeContainer.ts
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneFunctionDetailsPanel/components/CodeContainer/infrastructure/useFetchVCSFile.ts
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneFunctionDetailsPanel/components/GitHubContextProvider/infrastructure/PrivateVcsClient.ts
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneFunctionDetailsPanel/domain/types/FunctionDetails.ts
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneFunctionDetailsPanel/infrastructure/fetchCommitsInfo.ts
Labels: feat

#149 docs: Fix broken link in docs
  docs/sources/_index.md
Labels: type/docs

#157 chore: Upgrade @playwright/test to 1.47.0
  Dockerfile.plugin.e2e
  e2e/README.md
  package.json
  yarn.lock
Labels: chore

#158 chore: Update playwright version
  Dockerfile.plugin.e2e
Labels: chore

#153 chore: Add missing key to children component
  src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/ui/ExplorationTypeSelector.tsx
Labels: chore

#150 chore: Add tracking to the version number for better insights on user stats
  src/shared/domain/__tests__/reportInteraction.spec.ts
  src/shared/domain/reportInteraction.ts
Labels: chore

#155 chore: Add and use usePrevious hook to fix side-effect errors
  src/shared/components/QueryBuilder/QueryBuilder.tsx
  src/shared/components/QueryBuilder/ui/hooks.ts
Labels: chore

#162 docs(*): Update doc about using a local version of Grafana
  docker-compose.remote.yaml
  docs/GRAFANA-CROSS-DEVELOPMENT.md
Labels: type/docs

#163 fix(ExplainFlameGraph): Add tooltip when the LLM plugin is not installed
  src/pages/ProfilesExplorerView/components/SceneAiPanel/components/AiButton/AIButton.tsx
Labels: fix

#160 docs(*): Update for Explore Profiles
  docs/sources/_index.md
  docs/sources/access/index.md
  docs/sources/choose-a-view/index.md
  docs/sources/concepts/index.md
  docs/sources/determine-use-case/index.md
  docs/sources/get-started/index.md
  docs/sources/images/explore-profiles-view-bar.png
  docs/sources/investigate/index.md
Labels: type/docs

#166 docs(*): Fix issues in Explore Profiles docs
  docs/sources/_index.md
  docs/sources/get-started/index.md
Labels: documentation, type/docs, docs

#164 test(EndToEnd): Add diff flame graph view tests
  e2e/fixtures/pages/ExploreProfilesPage.ts
  e2e/fixtures/pages/PyroscopePage.ts
  e2e/tests/diff-flame-graph-view/diff-flame-graph.spec.ts
  e2e/tests/diff-flame-graph-view/diff-flame-graph.spec.ts-snapshots/Diff-flame-graph-view-Baseline-panel-Baseline-flame-graph-selection-mode-1-chromium-linux.png
  e2e/tests/diff-flame-graph-view/diff-flame-graph.spec.ts-snapshots/Diff-flame-graph-view-Baseline-panel-Baseline-time-picker-1-chromium-linux.png
  e2e/tests/diff-flame-graph-view/diff-flame-graph.spec.ts-snapshots/Diff-flame-graph-view-Baseline-panel-Baseline-time-picker-selection-mode-1-chromium-linux.png
  e2e/tests/diff-flame-graph-view/diff-flame-graph.spec.ts-snapshots/Diff-flame-graph-view-Comparison-panel-Comparison-flame-graph-selection-mode-1-chromium-linux.png
  e2e/tests/diff-flame-graph-view/diff-flame-graph.spec.ts-snapshots/Diff-flame-graph-view-Comparison-panel-Comparison-time-picker-1-chromium-linux.png
  e2e/tests/diff-flame-graph-view/diff-flame-graph.spec.ts-snapshots/Diff-flame-graph-view-Comparison-panel-Comparison-time-picker-selection-mode-1-chromium-linux.png
  e2e/tests/diff-flame-graph-view/diff-flame-graph.spec.ts-snapshots/Diff-flame-graph-view-Filters-Adding-a-filter-1-chromium-linux.png
  e2e/tests/diff-flame-graph-view/diff-flame-graph.spec.ts-snapshots/Diff-flame-graph-view-Main-UI-elements-1-chromium-linux.png
  e2e/tests/diff-flame-graph-view/diff-flame-graph.spec.ts-snapshots/Diff-flame-graph-view-Profile-type-selector-1-chromium-linux.png
  e2e/tests/diff-flame-graph-view/diff-flame-graph.spec.ts-snapshots/Diff-flame-graph-view-Service-selector-1-chromium-linux.png
  e2e/tests/flame-graph-view/flame-graph.spec.ts
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneComparePanel/SceneComparePanel.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneComparePanel/domain/actions/SwitchTimeRangeSelectionModeAction.tsx
  src/pages/ProfilesExplorerView/domain/variables/FiltersVariable/FiltersVariable.tsx
Labels: test

#169 fix(DiffFlameGraph): Remove non-working pprof export
  src/shared/components/FlameGraph/components/ExportMenu.tsx
  src/shared/components/FlameGraph/components/domain/useExportMenu.ts
Labels: fix

#170 test(EndToEnd): Add new script to upgrade Playwright
  Dockerfile.plugin.e2e
  e2e/README.md
  package.json
  scripts/upgrade-playwright
  yarn.lock
Labels: test

#171 fix(*): Fix useUrlSearchParams
  docs/sources/choose-a-view/index.md
  docs/sources/determine-use-case/index.md
  e2e/tests/settings-view/settings-view.spec.ts
  e2e/tests/settings-view/settings-view.spec.ts-snapshots/Plugin-Settings-Flame-graph-settings-Can-be-modified-for-the-Flame-graph-views-1-chromium-linux.png
  e2e/tests/settings-view/settings-view.spec.ts-snapshots/Plugin-Settings-Flame-graph-settings-Can-be-modified-for-the-Flame-graph-views-2-chromium-linux.png
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneDiffFlameGraph/infrastructure/useFetchDiffProfile.ts
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneFunctionDetailsPanel/components/CodeContainer/infrastructure/useFetchVCSFile.ts
  src/shared/domain/url-params/useUrlSearchParams.ts
Labels: fix

#174 fix(Faro): Fix Faro SDK config
  package.json
  src/app/infrastructure/__tests__/faro.spec.ts
  src/app/infrastructure/faro.ts
  yarn.lock
Labels: fix

#172 feat(AppHeader): Add Settings button
  e2e/tests/profile-types-view/profile-types.spec.ts
  e2e/tests/profile-types-view/profile-types.spec.ts-snapshots/Profile-types-view-Settings-button-1-chromium-linux.png
  src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/SceneProfilesExplorer.tsx
  src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/ui/ExplorationTypeSelector.tsx
  src/pages/SettingsView/SettingsView.tsx
  src/pages/SettingsView/domain/__tests__/useSettingsView.spec.ts
  src/pages/SettingsView/domain/useSettingsView.ts
  src/plugin.json
Labels: feat

#175 docs(Readme): Getting Started update
  README.md
Labels: type/docs

#176 docs(*): Make Explore Profiles docs public
  docs/sources/_index.md
Labels: type/docs

#179 ci: Update workflows to use actions that don't need organization secrets
  .github/workflows/publish-technical-documentation-next.yml
Labels: ci

#180 test(EndToEnd): Prevent flakiness by tweaking max diff pixel ratio in some cases
  e2e/tests/profile-types-view/profile-types.spec.ts
  e2e/tests/profile-types-view/profile-types.spec.ts-snapshots/Profile-types-view-Settings-button-1-chromium-linux.png
  e2e/tests/settings-view/settings-view.spec.ts
  e2e/tests/settings-view/settings-view.spec.ts-snapshots/Plugin-Settings-Flame-graph-settings-Can-be-modified-1-chromium-linux.png
  e2e/tests/settings-view/settings-view.spec.ts-snapshots/Plugin-Settings-Flame-graph-settings-Can-be-modified-2-chromium-linux.png
Labels: test

#181 docs(*): Update screenshots for docs
  docs/sources/choose-a-view/index.md
  docs/sources/images/explore-profiles-flamegraph-2.png
  docs/sources/images/explore-profiles-flamegraph.png
  docs/sources/images/explore-profiles-homescreen.png
  docs/sources/images/explore-profiles-labels-expand.png
  docs/sources/images/explore-profiles-labels-panel.png
  docs/sources/images/explore-profiles-labels.png
  docs/sources/images/explore-profiles-profile-types.png
  docs/sources/images/explore-profiles-select-flame-graph.gif
  docs/sources/images/explore-profiles-select-profile.png
  docs/sources/images/explore-profiles-selection.gif
  docs/sources/investigate/index.md
Labels: type/docs

#182 docs: Update README.md to call out profiles as being in preview
  README.md
Labels: type/docs

#183 docs: Update readme markdown
  README.md
Labels: type/docs

#178 docs(*): Add link to the documentation in the plugin info tooltip
  src/shared/ui/VersionInfoTooltip.tsx
Labels: type/docs

#185 docs(*): Update plugin README
  src/README.md
Labels: type/docs

#151 chore: accept pyroscope_git_session cookie name
  samples/provisioning-local/datasources/datasources.yaml
  samples/provisioning-remote/datasources/datasources.yaml
  samples/provisioning/datasources/datasources.yaml
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneFunctionDetailsPanel/components/GitHubContextProvider/infrastructure/GitSessionCookie.ts
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneFunctionDetailsPanel/components/GitHubContextProvider/infrastructure/GitSessionCookieManager.ts
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneFunctionDetailsPanel/components/GitHubContextProvider/infrastructure/__tests__/GitSessionCookieManager.spec.ts
Labels: chore

#189 refactor: Use relative URLs for API calls
  src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/SceneProfilesExplorer.tsx
  src/pages/ProfilesExplorerView/infrastructure/series/http/DataSourceProxyClient.ts
  src/shared/infrastructure/http/ApiClient.ts
  src/shared/infrastructure/http/__tests__/ApiClient.spec.ts
Labels: refactor

#190 docs: Add flame graph AI and intro video to doc
  docs/sources/_index.md
  docs/sources/choose-a-view/index.md
Labels: type/docs

#191 chore: fix formatting
  .github/workflows/publish-technical-documentation-next.yml
  docs/sources/investigate/index.md
  src/README.md
Labels: chore

#193 feat(QuickFilter): Add results count
  e2e/fixtures/pages/ExploreProfilesPage.ts
  e2e/tests/all-services-view/all-services.spec.ts
  e2e/tests/all-services-view/all-services.spec.ts-snapshots/All-services-view-Panel-actions-Flame-graph-action-1-chromium-linux.png
  e2e/tests/all-services-view/all-services.spec.ts-snapshots/All-services-view-Panel-actions-Labels-action-1-chromium-linux.png
  e2e/tests/favorites-view/favorites-view.spec.ts
  e2e/tests/favorites-view/favorites-view.spec.ts-snapshots/Favorites-view-Panel-actions-Labels-action-with-group-by-1-chromium-linux.png
  e2e/tests/favorites-view/favorites-view.spec.ts-snapshots/Favorites-view-Panel-actions-Labels-action-without-group-by-1-chromium-linux.png
  e2e/tests/flame-graph-view/flame-graph.spec.ts-snapshots/Flame-graph-view-Panel-actions-Labels-action-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Filters-Adding-a-filter-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Group-by-labels-selector-After-selecting-a-label-Panel-actions-Add-to-filters-action-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Group-by-labels-selector-Selects-a-label-and-displays-the-breakdown-in-a-new-grid-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Layout-switcher-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Main-UI-elements-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Panel-actions-Select-action-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Panel-type-switcher-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Panel-type-switcher-2-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Profile-type-selector-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Service-selector-1-chromium-linux.png
  e2e/tests/profile-types-view/profile-types.spec.ts
  e2e/tests/profile-types-view/profile-types.spec.ts-snapshots/Profile-types-view-Panel-actions-Labels-action-1-chromium-linux.png
  src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/SceneByVariableRepeaterGrid.tsx
  src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/components/SceneQuickFilter.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreAllServices/SceneExploreAllServices.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreFavorites/SceneExploreFavorites.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/components/SceneGroupByLabels/SceneGroupByLabels.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/components/SceneGroupByLabels/components/SceneLabelValuesGrid/SceneLabelValuesGrid.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceProfileTypes/SceneExploreServiceProfileTypes.tsx
  src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/SceneProfilesExplorer.tsx
Labels: feat

#194 feat(*): Minor UI improvements (timeseries point size, plugin info tooltip)
  src/pages/ProfilesExplorerView/components/SceneLabelValuesTimeseries.tsx
  src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/SceneProfilesExplorer.tsx
  src/shared/ui/PageTitle.tsx
  src/shared/ui/PluginInfo.tsx
  src/shared/ui/VersionInfoTooltip.tsx
Labels: enhancement, feat
