Repository grafana/profiles-drilldown, pull requests merged in 2024-10, with the labels that each got.

#205 fix(Filters): ensure "is empty" filter is synced with URL
  src/pages/ProfilesExplorerView/domain/variables/FiltersVariable/FiltersVariable.tsx
  src/pages/ProfilesExplorerView/domain/variables/FiltersVariable/filters-ops.tsx
  src/shared/components/QueryBuilder/domain/actions.ts
  src/shared/components/QueryBuilder/domain/helpers/__tests__/queryToFilters.spec.ts
  src/shared/components/QueryBuilder/domain/helpers/queryToFilters.ts
  src/shared/components/QueryBuilder/domain/types.ts
Labels: fix

#207 fix(QueryBuilder): Filters with regex values can be edited in place
  src/shared/components/QueryBuilder/domain/helpers/__tests__/queryToFilters.spec.ts
  src/shared/components/QueryBuilder/domain/helpers/queryToFilters.ts
  src/shared/components/QueryBuilder/domain/states/loadLabelValues.ts
  src/shared/components/QueryBuilder/domain/types.ts
  src/shared/components/QueryBuilder/infrastructure/operatorsRepository.ts
  src/shared/components/QueryBuilder/ui/constants.ts
  src/shared/components/QueryBuilder/ui/inputs/SingleEditionInput.tsx
  src/shared/components/QueryBuilder/ui/selects/SingleEditionSelect.tsx
  src/shared/components/QueryBuilder/ui/selects/SingleSelect.tsx
Labels: fix

#209 docs(Contributing): Add missing domain logic layer doc
  docs/CODE-ARCHITECTURE.md
Labels: type/docs

#211 feat(*): Minor improvements
  src/pages/ProfilesExplorerView/components/SceneLabelValuesHistogram.tsx
  src/pages/ProfilesExplorerView/components/SceneLabelValuesTimeseries.tsx
  src/pages/ProfilesExplorerView/domain/variables/FiltersVariable/FiltersVariable.tsx
  src/shared/components/QueryBuilder/ui/chiclets/Chiclet.tsx
  src/shared/components/QueryBuilder/ui/chiclets/ChicletAttributeOperator.tsx
  src/shared/components/QueryBuilder/ui/chiclets/ChicletAttributeOperatorValue.tsx
Labels: feat

#212 feat(StatsPanel): Add title on hover value + vertical border to separate compare actions
  src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/components/SceneGroupByLabels/components/SceneLabelValuesGrid/components/SceneStatsPanel/SceneStatsPanel.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/components/SceneGroupByLabels/components/SceneLabelValuesGrid/components/SceneStatsPanel/ui/CompareAction.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/components/SceneGroupByLabels/components/SceneLabelValuesGrid/components/SceneStatsPanel/ui/StatsPanel.tsx
  src/shared/components/QueryBuilder/ui/chiclets/Chiclet.tsx
Labels: feat

#218 fix(Header): Fix sticky header position in Grafana v11.3+
  Dockerfile.plugin.e2e
  package.json
  src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/SceneProfilesExplorer.tsx
  yarn.lock
Labels: fix

#214 chore(*): Add knip to cleanup unused code
  package.json
  src/app/components/Onboarding/ui/OnboardingModal.tsx
  src/empty.json
  src/pages/ProfilesExplorerView/components/SceneAiPanel/infrastructure/ProfileApiClient.ts
  src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/components/SceneEmptyState/ui/EmptyState.tsx
  src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/components/SceneEmptyState/ui/GrotNotFound.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneComparePanel/SceneComparePanel.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneComparePanel/domain/actions/SwitchTimeRangeSelectionModeAction.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneComparePanel/domain/events/EventSwitchTimerangeSelectionMode.ts
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneComparePanel/ui/colors.ts
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneFunctionDetailsPanel/components/AiSuggestionsPanel/domain/useOpenAiSuggestions.ts
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneFunctionDetailsPanel/components/CodeContainer/ui/Code.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/components/SceneGroupByLabels/components/SceneLabelValuesGrid/SceneLabelValuesGrid.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/components/SceneGroupByLabels/components/SceneLabelValuesGrid/components/SceneStatsPanel/ui/StatsPanel.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/components/SceneGroupByLabels/domain/events/EventSelectForCompare.tsx
  src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/SceneProfilesExplorer.tsx
  src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/ui/ExplorationTypeSelector.tsx
  src/pages/ProfilesExplorerView/domain/actions/CompareAction.tsx
  src/pages/ProfilesExplorerView/domain/actions/FavAction.tsx
  src/pages/ProfilesExplorerView/domain/events/EventTimeseriesDataReceived.ts
  src/pages/ProfilesExplorerView/domain/events/EventViewDiffFlameGraph.tsx
  src/pages/ProfilesExplorerView/domain/variables/FiltersVariable/filters-ops.tsx
  src/pages/ProfilesExplorerView/infrastructure/helpers/getDataSourceError.ts
  src/pages/ProfilesExplorerView/infrastructure/pyroscope-data-sources.ts
  src/pages/ProfilesExplorerView/infrastructure/series/helpers/getProfileMetricUnit.ts
  src/shared/components/AiPanel/components/AIButton.tsx
  src/shared/components/AiPanel/components/AiReply.tsx
  src/shared/components/AiPanel/components/FollowUpForm.tsx
  src/shared/components/AiPanel/domain/buildLlmPrompts.ts
  src/shared/components/AiPanel/domain/useOpenAiChatCompletions.ts
  src/shared/components/AiPanel/infrastructure/useFetchLlmPluginStatus.ts
  src/shared/components/FlameGraph/components/infrastructure/PprofRequestWithoutMaxNodes.ts
  src/shared/components/FlameGraph/components/infrastructure/pprofApiClient.ts
  src/shared/components/FlameGraph/domain/flamebearerToDataFrameDTO.ts
  src/shared/components/QueryBuilder/QueryBuilder.tsx
  src/shared/components/QueryBuilder/domain/helpers/queryToFilters.ts
  src/shared/components/QueryBuilder/domain/types.ts
  src/shared/components/QueryBuilder/ui/chiclets/ChicletsList.tsx
  src/shared/components/QueryBuilder/ui/inputs/SingleEditionInput.tsx
  src/shared/components/QueryBuilder/ui/selects/MultipleEditionSelect.tsx
  src/shared/components/QueryBuilder/ui/selects/MultipleSelect.tsx
  src/shared/components/QueryBuilder/ui/selects/SingleEditionSelect.tsx
  src/shared/domain/useToggleSidePanel.ts
  src/shared/infrastructure/profile-metrics/getProfileMetric.ts
  src/shared/infrastructure/settings/settingsApiClient.ts
  src/shared/ui/Panel/GrafanaPanelBox/GrafanaPanelBox.tsx
  src/shared/ui/Panel/GrafanaPanelBox/PanelMenu.tsx
  src/shared/ui/Panel/GrafanaPanelBox/PanelStatus.tsx
  src/shared/ui/Panel/GrafanaPanelBox/TitleItem.tsx
  yarn.lock
Labels: chore

#221 refactor(Ai): Add official LLM package
  package.json
  src/pages/ProfilesExplorerView/components/SceneAiPanel/components/AiButton/infrastructure/useFetchLlmPluginStatus.ts
  src/pages/ProfilesExplorerView/components/SceneAiPanel/domain/useOpenAiChatCompletions.ts
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneFunctionDetailsPanel/components/AiSuggestionsPanel/domain/useOpenAiSuggestions.ts
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneFunctionDetailsPanel/components/CodeContainer/ui/Code.tsx
  yarn.lock
Labels: refactor

#222 feat(ServiceNameVariable): Persist last service selected in localStorage
  src/pages/ProfilesExplorerView/domain/variables/ServiceNameVariable/ServiceNameVariable.tsx
Labels: feat

#227 chore(Faro): Adjust user info
  src/app/infrastructure/__tests__/faro.spec.ts
  src/app/infrastructure/faro.ts
  src/app/infrastructure/getUserInfo.ts
Labels: chore

#228 feat(DiffFlameGraph): Add "how to" infos
  e2e/tests/diff-flame-graph-view/diff-flame-graph.spec.ts
  e2e/tests/diff-flame-graph-view/diff-flame-graph.spec.ts-snapshots/Diff-flame-graph-view-Baseline-panel-Baseline-time-picker-1-chromium-linux.png
  e2e/tests/diff-flame-graph-view/diff-flame-graph.spec.ts-snapshots/Diff-flame-graph-view-Baseline-panel-Baseline-time-picker-selection-mode-1-chromium-linux.png
  e2e/tests/diff-flame-graph-view/diff-flame-graph.spec.ts-snapshots/Diff-flame-graph-view-Comparison-panel-Comparison-time-picker-1-chromium-linux.png
  e2e/tests/diff-flame-graph-view/diff-flame-graph.spec.ts-snapshots/Diff-flame-graph-view-Comparison-panel-Comparison-time-picker-selection-mode-1-chromium-linux.png
  e2e/tests/diff-flame-graph-view/diff-flame-graph.spec.ts-snapshots/Diff-flame-graph-view-Service-selector-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Group-by-labels-selector-After-sel-dbe5f-n-items-then-clicking-on-the-Compare-button-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Group-by-labels-selector-After-sel-f81f2-on-item-then-clicking-on-the-Compare-button-1-chromium-linux.png
  src/app/components/Onboarding/ui/OnboardingModal.tsx
  src/img/diff-view-how-to.gif
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneComparePanel/domain/actions/SwitchTimeRangeSelectionModeAction.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneDiffFlameGraph/SceneDiffFlameGraph.tsx
  src/shared/ui/InlineBanner.tsx
  webpack.config.ts
Labels: feat

#229 refactor(AppHeader): Split responsibilities
  src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/SceneProfilesExplorer.tsx
  src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/components/Header.tsx
  src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/components/domain/__tests__/builsShareableUrl.spec.ts
  src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/components/domain/builsShareableUrl.ts
  src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/components/domain/useHeader.ts
  src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/components/ui/ExplorationTypeSelector.tsx
Labels: refactor

#233 fix(DiffView): Ensure ranges are initialized when landing
  src/pages/ProfilesExplorerView/domain/variables/ServiceNameVariable/ServiceNameVariable.tsx
Labels: fix

#234 fix(SettingsView): Fix back button after modifying the max nodes setting
  src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/components/domain/useHeader.ts
  src/pages/SettingsView/domain/__tests__/useSettingsView.spec.ts
  src/pages/SettingsView/domain/useSettingsView.ts
Labels: fix

#235 fix(LabelValuesGrid): decrease column size to accommodate small screen resolutions
  e2e/tests/favorites-view/favorites-view.spec.ts-snapshots/Favorites-view-Panel-actions-Labels-action-with-group-by-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Group-by-labels-selector-After-selecting-a-label-Panel-actions-Add-to-filters-action-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Group-by-labels-selector-Selects-a-label-and-displays-the-breakdown-in-a-new-grid-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Panel-actions-Select-action-1-chromium-linux.png
  src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/components/SceneGroupByLabels/components/SceneLabelValuesGrid/SceneLabelValuesGrid.tsx
Labels: fix

#230 feat(AppHeader): Revamp header
  e2e/tests/favorites-view/favorites-view.spec.ts-snapshots/Favorites-view-Panel-actions-Expand-panel-action-1-chromium-linux.png
  src/app/App.tsx
  src/pages/ProfilesExplorerView/components/GiveFeedbackButton.tsx
  src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/components/SceneQuickFilter.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneDiffFlameGraph/SceneDiffFlameGraph.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/SceneFlameGraph.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/components/SceneGroupByLabels/SceneGroupByLabels.tsx
  src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/SceneProfilesExplorer.tsx
  src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/components/Header.tsx
  src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/components/ui/ExplorationTypeSelector.tsx
  src/pages/ProfilesExplorerView/domain/variables/FiltersVariable/FiltersVariable.tsx
  src/pages/ProfilesExplorerView/domain/variables/GroupByVariable/GroupByVariable.tsx
  src/pages/ProfilesExplorerView/domain/variables/ProfileMetricVariable.tsx
  src/pages/ProfilesExplorerView/domain/variables/ServiceNameVariable/ServiceNameVariable.tsx
  src/shared/components/QueryBuilder/QueryBuilder.tsx
  src/shared/ui/PageTitle.tsx
  src/shared/ui/PyroscopeLogo.tsx
Labels: feat

#241 chore(Header): Add slight contrast to the exploration pills
  src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/components/ui/ExplorationTypeSelector.tsx
Labels: chore

#244 fix(ShareableUrl): Fix link generation when the default time range is selected
  src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/components/domain/__tests__/builsShareableUrl.spec.ts
  src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/components/domain/builsShareableUrl.ts
Labels: fix

#248 fix(*): Small UI fixes
  src/pages/ProfilesExplorerView/components/SceneAiPanel/components/AiButton/AIButton.tsx
  src/shared/components/QueryBuilder/ui/chiclets/Chiclet.tsx
Labels: fix

#231 feat(DiffView): Add CTAs and comparison presets
  e2e/tests/diff-flame-graph-view/diff-flame-graph.spec.ts
  e2e/tests/diff-flame-graph-view/diff-flame-graph.spec.ts-snapshots/Diff-flame-graph-view-Baseline-panel-Baseline-time-picker-1-chromium-linux.png
  e2e/tests/diff-flame-graph-view/diff-flame-graph.spec.ts-snapshots/Diff-flame-graph-view-Baseline-panel-Baseline-time-picker-selection-mode-1-chromium-linux.png
  e2e/tests/diff-flame-graph-view/diff-flame-graph.spec.ts-snapshots/Diff-flame-graph-view-Comparison-panel-Comparison-time-picker-1-chromium-linux.png
  e2e/tests/diff-flame-graph-view/diff-flame-graph.spec.ts-snapshots/Diff-flame-graph-view-Comparison-panel-Comparison-time-picker-selection-mode-1-chromium-linux.png
  e2e/tests/diff-flame-graph-view/diff-flame-graph.spec.ts-snapshots/Diff-flame-graph-view-Service-selector-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Group-by-labels-selector-After-sel-dbe5f-n-items-then-clicking-on-the-Compare-button-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Group-by-labels-selector-After-sel-f81f2-on-item-then-clicking-on-the-Compare-button-1-chromium-linux.png
  src/pages/ProfilesExplorerView/components/GiveFeedbackButton.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/SceneExploreDiffFlameGraph.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneComparePanel/SceneComparePanel.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneComparePanel/components/SceneTimeRangeWithAnnotations.ts
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneDiffFlameGraph/SceneDiffFlameGraph.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneDiffFlameGraph/ui/MissingSelectionsBanner.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/ScenePresetsPicker/ScenePresetsPicker.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/domain/events/EventDiffAutoSelect.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/domain/events/EventDiffChoosePreset.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/SceneFlameGraph.tsx
  src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/SceneProfilesExplorer.tsx
  src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/components/Header.tsx
  src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/components/domain/builsShareableUrl.ts
  src/pages/ProfilesExplorerView/domain/buildTimeRange.ts
  src/pages/ProfilesExplorerView/domain/getDefaultTimeRange.ts
  src/shared/domain/reportInteraction.ts
  src/shared/ui/PageTitle.tsx
  src/shared/ui/PyroscopeLogo.tsx
Labels: feat

#249 feat(TimeSeries): Add menu with scale options
  src/pages/ProfilesExplorerView/components/SceneLabelValuesTimeseries.tsx
Labels: feat

#252 build(Bundle): Add BundleWatch to CI
  .github/workflows/ci.yml
  package.json
  yarn.lock
Labels: build

#251 fix(Timeseries): Persist scale when data changes
  src/pages/ProfilesExplorerView/components/SceneLabelValuesTimeseries.tsx
Labels: fix

#210 feat(LabelsView): Include/exclude panel actions
  e2e/tests/favorites-view/favorites-view.spec.ts-snapshots/Favorites-view-Panel-actions-Labels-action-with-group-by-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Group-by-labels-selector-After-selecting-a-label-Panel-actions-Add-to-filters-action-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Group-by-labels-selector-Selects-a-label-and-displays-the-breakdown-in-a-new-grid-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Panel-actions-Select-action-1-chromium-linux.png
  src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/components/SceneGroupByLabels/SceneGroupByLabels.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/components/SceneGroupByLabels/components/SceneLabelValuesGrid/SceneLabelValuesGrid.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/components/SceneGroupByLabels/components/SceneLabelValuesGrid/infrastructure/buildLabelValuesGridQueryRunner.ts
  src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/components/SceneGroupByLabels/domain/actions/IncludeExcludeAction/IncludeExcludeAction.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/components/SceneGroupByLabels/domain/actions/IncludeExcludeAction/ui/FilterButtons.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/components/SceneGroupByLabels/domain/events/EventClearLabelFromFilters.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/components/SceneGroupByLabels/domain/events/EventExcludeLabelFromFilters.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/components/SceneGroupByLabels/domain/events/EventIncludeLabelInFilters.tsx
  src/pages/ProfilesExplorerView/domain/actions/SelectAction.tsx
  src/pages/ProfilesExplorerView/domain/events/EventAddLabelToFilters.tsx
  src/pages/ProfilesExplorerView/domain/variables/FiltersVariable/__tests__/filter-ops.spec.ts
  src/pages/ProfilesExplorerView/domain/variables/FiltersVariable/filters-ops.ts
  src/pages/ProfilesExplorerView/domain/variables/FiltersVariable/filters-ops.tsx
  src/shared/domain/reportInteraction.ts
Labels: feat
