Repository grafana/profiles-drilldown, pull requests merged in 2024-12, with the labels that each got.

#305 ci: Format drone migration yaml file
  .drone.migration.jsonnet
  drone_migration.yaml
Labels: ci

#304 refactor(*): Use the Intl API for sorting items
  src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/domain/sortFavGridItems.ts
  src/pages/ProfilesExplorerView/components/SceneExploreFavorites/SceneExploreFavorites.tsx
  src/pages/ProfilesExplorerView/domain/variables/ProfileMetricVariable.tsx
  src/pages/ProfilesExplorerView/infrastructure/series/formatSeriesToProfileMetrics.ts
  src/pages/ProfilesExplorerView/infrastructure/series/formatSeriesToServices.ts
  src/shared/components/QueryBuilder/ui/selects/MultipleEditionSelect.tsx
  src/shared/domain/localeCompare.ts
Labels: refactor

#312 fix(Header): Prevent crash if useChromeHeaderHeight is not available (for Grafana < v11.3)
  src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/components/Header.tsx
Labels: fix

#313 fix(DiffFlameGraphView): Clear preset option when applying auto-select
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneComparePanel/SceneComparePanel.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/ScenePresetsPicker/ScenePresetsPicker.tsx
Labels: fix

#301 feat(*): Add investigations support
  src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/SceneByVariableRepeaterGrid.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneComparePanel/SceneComparePanel.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/components/SceneGroupByLabels/components/SceneLabelValuesGrid/components/SceneLabelValuePanel.tsx
  src/pages/ProfilesExplorerView/components/SceneLabelValuesTimeseries/SceneLabelValuesTimeseries.tsx
  src/pages/ProfilesExplorerView/components/SceneLabelValuesTimeseries/SceneTimeseriesMenu.tsx
  src/pages/ProfilesExplorerView/components/SceneMainServiceTimeseries.tsx
  src/pages/ProfilesExplorerView/domain/useGetPluginExtensionLink.ts
  src/pages/ProfilesExplorerView/domain/variables/ServiceNameVariable/ServiceNameVariable.tsx
  src/pages/ProfilesExplorerView/helpers/__tests__/getExploreUrl.spec.ts
  src/pages/ProfilesExplorerView/helpers/getExploreUrl.ts
  src/pages/ProfilesExplorerView/helpers/vizPanelBuilder.ts
  src/plugin.json
Labels: feat

#316 fix(QueryRunners): Prevent invalid queries to run
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneComparePanel/infrastructure/buildCompareTimeSeriesQueryRunner.ts
  src/pages/ProfilesExplorerView/infrastructure/flame-graph/buildFlameGraphQueryRunner.ts
  src/pages/ProfilesExplorerView/infrastructure/timeseries/buildTimeSeriesQueryRunner.ts
  src/pages/ProfilesExplorerView/infrastructure/withPreventInvalidQuery.ts
Labels: fix

#318 chore: Update profile type descriptions
  e2e/fixtures/pages/ExploreProfilesPage.ts
  e2e/tests/all-services-view/all-services.spec.ts
  e2e/tests/all-services-view/all-services.spec.ts-snapshots/All-services-view-Panel-actions-Flame-graph-action-1-chromium-linux.png
  e2e/tests/all-services-view/all-services.spec.ts-snapshots/All-services-view-Panel-actions-Labels-action-1-chromium-linux.png
  e2e/tests/diff-flame-graph-view/diff-flame-graph.spec.ts
  e2e/tests/diff-flame-graph-view/diff-flame-graph.spec.ts-snapshots/Diff-flame-graph-view-Baseline-panel-Baseline-flame-graph-selection-mode-1-chromium-linux.png
  e2e/tests/diff-flame-graph-view/diff-flame-graph.spec.ts-snapshots/Diff-flame-graph-view-Baseline-panel-Baseline-time-picker-1-chromium-linux.png
  e2e/tests/diff-flame-graph-view/diff-flame-graph.spec.ts-snapshots/Diff-flame-graph-view-Baseline-panel-Baseline-time-picker-selection-mode-1-chromium-linux.png
  e2e/tests/diff-flame-graph-view/diff-flame-graph.spec.ts-snapshots/Diff-flame-graph-view-Comparison-panel-Comparison-flame-graph-selection-mode-1-chromium-linux.png
  e2e/tests/diff-flame-graph-view/diff-flame-graph.spec.ts-snapshots/Diff-flame-graph-view-Comparison-panel-Comparison-time-picker-1-chromium-linux.png
  e2e/tests/diff-flame-graph-view/diff-flame-graph.spec.ts-snapshots/Diff-flame-graph-view-Comparison-panel-Comparison-time-picker-selection-mode-1-chromium-linux.png
  e2e/tests/diff-flame-graph-view/diff-flame-graph.spec.ts-snapshots/Diff-flame-graph-view-Filters-Adding-a-filter-1-chromium-linux.png
  e2e/tests/diff-flame-graph-view/diff-flame-graph.spec.ts-snapshots/Diff-flame-graph-view-Main-UI-elements-1-chromium-linux.png
  e2e/tests/diff-flame-graph-view/diff-flame-graph.spec.ts-snapshots/Diff-flame-graph-view-Profile-type-selector-1-chromium-linux.png
  e2e/tests/diff-flame-graph-view/diff-flame-graph.spec.ts-snapshots/Diff-flame-graph-view-Service-selector-1-chromium-linux.png
  e2e/tests/diff-flame-graph-view/diff-flame-graph.spec.ts-snapshots/Diff-flame-graph-view-Sync-time-ranges-Syncing-flame-graph-range-selection-1-chromium-linux.png
  e2e/tests/diff-flame-graph-view/diff-flame-graph.spec.ts-snapshots/Diff-flame-graph-view-Sync-time-ranges-Syncing-time-picker-range-selection-1-chromium-linux.png
  e2e/tests/favorites-view/favorites-view.spec.ts-snapshots/Favorites-view-Layout-switcher-1-chromium-linux.png
  e2e/tests/favorites-view/favorites-view.spec.ts-snapshots/Favorites-view-Panel-actions-Expand-panel-action-1-chromium-linux.png
  e2e/tests/favorites-view/favorites-view.spec.ts-snapshots/Favorites-view-Panel-actions-Flame-graph-action-1-chromium-linux.png
  e2e/tests/favorites-view/favorites-view.spec.ts-snapshots/Favorites-view-Panel-actions-Labels-action-with-group-by-1-chromium-linux.png
  e2e/tests/favorites-view/favorites-view.spec.ts-snapshots/Favorites-view-Panel-actions-Labels-action-without-group-by-1-chromium-linux.png
  e2e/tests/flame-graph-view/flame-graph.spec.ts
  e2e/tests/flame-graph-view/flame-graph.spec.ts-snapshots/Flame-graph-view-Filters-Adding-a-filter-1-chromium-linux.png
  e2e/tests/flame-graph-view/flame-graph.spec.ts-snapshots/Flame-graph-view-Main-UI-elements-1-chromium-linux.png
  e2e/tests/flame-graph-view/flame-graph.spec.ts-snapshots/Flame-graph-view-Panel-actions-Labels-action-1-chromium-linux.png
  e2e/tests/flame-graph-view/flame-graph.spec.ts-snapshots/Flame-graph-view-Profile-type-selector-1-chromium-linux.png
  e2e/tests/flame-graph-view/flame-graph.spec.ts-snapshots/Flame-graph-view-Service-selector-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Filters-Adding-a-filter-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Group-by-labels-selector-After-sel-dbe5f-n-items-then-clicking-on-the-Compare-button-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Group-by-labels-selector-After-sel-f81f2-on-item-then-clicking-on-the-Compare-button-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Group-by-labels-selector-After-selecting-a-label-Panel-actions-Flame-graph-action-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Layout-switcher-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Main-UI-elements-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Panel-actions-Expand-panel-action-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Panel-type-switcher-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Profile-type-selector-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Service-selector-1-chromium-linux.png
  e2e/tests/onboarding-view/onboarding.spec.ts-snapshots/Onboarding-displays-an-onboarding-modal-that-can-be-closed-3-chromium-linux.png
  e2e/tests/profile-types-view/profile-types.spec.ts-snapshots/Profile-types-view-Panel-actions-Flame-graph-action-1-chromium-linux.png
  e2e/tests/profile-types-view/profile-types.spec.ts-snapshots/Profile-types-view-Panel-actions-Labels-action-1-chromium-linux.png
  src/shared/infrastructure/profile-metrics/profile-metrics.json
Labels: chore

#220 feat(*): Add query link extension
  drone_migration.yaml
  src/links.ts
  src/module.ts
  src/plugin.json
Labels: feat

#320 chore(*): Upgrade React router v6
  .config/.cprc.json
  .config/.eslintrc
  .config/Dockerfile
  .config/README.md
  .config/entrypoint.sh
  .config/jest-setup.js
  .config/jest.config.js
  .config/jest/utils.js
  .config/supervisord/supervisord.conf
  .config/tsconfig.json
  .config/webpack/BuildModeWebpackPlugin.ts
  .config/webpack/utils.ts
  .config/webpack/webpack.config.ts
  .cprc.json
  Dockerfile.remote
  docker-compose.e2e.yaml
  docker-compose.local.yaml
  docker-compose.remote.yaml
  docker-compose.yaml
  package.json
  src/app/components/Routes/Routes.tsx
  src/app/components/Routes/domain/useNavigationLinksUpdate.ts
  src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/components/domain/useHeader.ts
  src/pages/SettingsView/SettingsView.tsx
  src/pages/SettingsView/domain/__tests__/useSettingsView.spec.ts
  src/pages/SettingsView/domain/useSettingsView.ts
  src/plugin.json
  src/shared/domain/url-params/useUrlSearchParams.ts
  src/shared/infrastructure/tracking/faro/__tests__/faro.spec.ts
  tsconfig.json
  webpack.config.ts
  yarn.lock
Labels: chore

#323 revert: "perf(*): Lazy load page components"
  src/app/components/Routes/Routes.tsx
  src/pages/AdHocView/AdHocView.tsx
  src/pages/ProfilesExplorerView/ProfilesExplorerView.tsx
  src/pages/SettingsView/SettingsView.tsx
Labels: revert
