Repository grafana/profiles-drilldown, pull requests merged in 2025-02, with the labels that each got.

#375 ci: Use refs for reusable workflows
  .github/workflows/ci.yml
  .github/workflows/deploy-existing-version.yml
Labels: ci

#373 fix(FunctionDetailsPanel): Fix start ellipsis for file names containing non-alpha chars
  e2e/tests/flame-graph-view/github-integration.spec.ts
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneFunctionDetailsPanel/SceneFunctionDetailsPanel.tsx
Labels: fix

#378 ci: Fix deploy file name
  .github/workflows/deploy.yml
Labels: ci

#374 fix(Filters): Ensure filters are always cleared when changing the data source or the service
  src/pages/ProfilesExplorerView/components/SceneMainServiceTimeseries.tsx
  src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/SceneProfilesExplorer.tsx
  src/pages/ProfilesExplorerView/domain/variables/FiltersVariable/FiltersVariable.tsx
  src/pages/ProfilesExplorerView/domain/variables/ServiceNameVariable/ServiceNameVariable.tsx
Labels: fix

#377 chore: Track Ad Hoc view
  src/pages/AdHocView/ui/tabs/AdHocSingle.tsx
  src/shared/domain/reportInteraction.ts
Labels: chore

#376 ci: Refactor actions to make it easier to reuse them
  .github/workflows/build.yml
  .github/workflows/ci.yml
  .github/workflows/package.yml
Labels: ci

#384 fix(Settings): Prevent warning to be displayed when no settings is returned by the Settings API
  src/shared/infrastructure/settings/settingsApiClient.ts
Labels: fix

#385 feat(AdHocView): Remove Grafana menu item to the Ad Hoc view
  src/app/App.tsx
  src/app/Routes.tsx
  src/app/components/Routes/Routes.tsx
  src/app/components/Routes/domain/useNavigationLinksUpdate.ts
  src/constants.ts
  src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/components/Header.tsx
  src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/components/domain/useHeader.ts
  src/pages/SettingsView/domain/useSettingsView.ts
  src/plugin.json
  src/shared/domain/__tests__/reportInteraction.spec.ts
  src/shared/domain/reportInteraction.ts
Labels: feat

#379 ci: Create a workflow for manual releases
  .drone.migration.jsonnet
  .github/workflows/change-version-in-plugins-catalog.yml
  .github/workflows/create-new-version.yml
  .github/workflows/update-plugins-catalog.yml
  drone_migration.yaml
Labels: ci

#388 ci: Add missing props based on validation errors
  .github/workflows/change-version-in-plugins-catalog.yml
  .github/workflows/deploy-existing-version.yml
Labels: ci

#391 ci(Docker): Disable all plugin preinstalls to prevent clashes
  docker-compose.e2e.yaml
  docker-compose.local.yaml
  docker-compose.remote.yaml
  docker-compose.yaml
Labels: ci

#387 ci: Disable e2e when creating a new version
  .github/workflows/build.yml
  .github/workflows/ci.yml
  .github/workflows/create-new-version.yml
Labels: ci

#389 ci: Release existing version
  .github/workflows/cut-new-release.yml
  .github/workflows/release-existing-version.yml
Labels: ci

#394 ci: Change flows to run jobs in sequence
  .github/workflows/cut-new-release.yml
  .github/workflows/release-existing-version.yml
Labels: ci

#395 fix(Faro): Narrow down frontend logging to plugin URL
  src/shared/infrastructure/tracking/faro/faro.ts
Labels: fix

#396 ci: Make sure update-prod-catalog can be run
  .github/workflows/change-version-in-plugins-catalog.yml
  .github/workflows/cut-new-release.yml
  .github/workflows/deploy-existing-version.yml
  .github/workflows/release-existing-version.yml
Labels: ci

#397 ci: Change the cloud deployment workflow to allow deploying to specified environment
  .github/workflows/deploy-existing-version.yml
Labels: ci

#399 ci: Always use sha in version.ts
  .github/workflows/build.yml
  .github/workflows/ci.yml
  .github/workflows/cut-new-release.yml
  .github/workflows/release-existing-version.yml
Labels: ci

#400 ci: Get correct sha for builds
  .github/workflows/build.yml
Labels: ci

#401 ci: Update Trigger Argo Workflow actions
  .github/workflows/deploy.yml
Labels: ci

#402 ci: Run test coverage only in pull requests
  .github/workflows/build.yml
Labels: ci

#404 ci: Remove debug step and add emoji to important steps
  .github/workflows/cut-new-release.yml
  .github/workflows/deploy-existing-version.yml
  .github/workflows/deploy.yml
Labels: ci

#406 ci: Rename package to upload
  .github/workflows/ci.yml
  .github/workflows/cut-new-release.yml
  .github/workflows/release-existing-version.yml
  .github/workflows/upload.yml
Labels: ci

#407 fix(FlameGraph): Always render an error message when loading fails
  docker-compose.e2e.yaml
  docker-compose.local.yaml
  docker-compose.remote.yaml
  docker-compose.yaml
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/SceneFlameGraph.tsx
Labels: fix

#413 ci: Use correct github.actor to prevent CI builds on tags
  .github/workflows/ci.yml
Labels: ci

#414 ci: Trigger unique Argo workflows
  .github/workflows/deploy.yml
Labels: ci

#415 ci: Use shorter sha for Argo workflows
  .github/workflows/deploy.yml
Labels: ci

#411 ci: Run deployments in sequence
  .github/workflows/cut-new-release.yml
Labels: ci

#408 feat(Tracking): Add page view tracking
  src/pages/AdHocView/AdHocView.tsx
  src/pages/ProfilesExplorerView/ProfilesExplorerView.tsx
  src/pages/SettingsView/SettingsView.tsx
  src/shared/domain/reportInteraction.ts
  src/shared/infrastructure/tracking/useReportPageInitialized.ts
Labels: feat

#422 fix(*): Remove lazy loading of page components
  src/app/Routes.tsx
Labels: fix

#416 feat: Jarben/deploy pipelines extension change
  src/extensions/DeployPipelinesExtension.tsx
  src/extensions/IntegrationExtension.tsx
  src/pages/SettingsView/DeployIntegration.tsx
  src/pages/SettingsView/components/CollectorSettings/components/ViewRule/ViewRule.tsx
  src/plugin.json
Labels: feat

#398 feat(App): Changes for GA
  README.md
  docs/sources/_index.md
  docs/sources/access/_index.md
  docs/sources/access/profile-settings.md
  docs/sources/choose-a-view/index.md
  docs/sources/concepts/_index.md
  docs/sources/determine-use-case/index.md
  docs/sources/get-started/index.md
  docs/sources/images/explore-profiles-settings.png
  docs/sources/investigate/_index.md
  src/README.md
  src/pages/ProfilesExplorerView/components/GiveFeedbackButton.tsx
Labels: type/docs, feat

#427 fix(Routes): Add redirection for non-supported paths
  e2e/fixtures/pages/ExploreProfilesPage.ts
  src/app/Routes.tsx
Labels: fix

#426 ci: Fix GitHub release creation of a major version
  .github/workflows/cut-new-release.yml
Labels: ci

#432 docs: Review copy
  docs/sources/_index.md
  docs/sources/access/_index.md
  docs/sources/access/profile-settings.md
  docs/sources/choose-a-view/index.md
  docs/sources/concepts/_index.md
  docs/sources/determine-use-case/index.md
  docs/sources/get-started/index.md
  docs/sources/images/explore-profiles-homescreen.png
  docs/sources/investigate/_index.md
  docs/sources/investigate/flame-graph-ai.md
Labels: type/docs

#429 feat(investigations): adapt to changed plugin id
  src/pages/ProfilesExplorerView/domain/useGetPluginExtensionLink.ts
  src/plugin.json
Labels: feat

#430 feat: Rename Explore Profiles to Grafana Profiles Drilldown
  README.md
  docs/CODE-ARCHITECTURE.md
  docs/CONTRIBUTING.md
  docs/GRAFANA-CROSS-DEVELOPMENT.md
  docs/README.md
  docs/sources/_index.md
  docs/sources/access/_index.md
  docs/sources/access/profile-settings.md
  docs/sources/choose-a-view/index.md
  docs/sources/concepts/_index.md
  docs/sources/determine-use-case/index.md
  docs/sources/images/explore-profiles-homescreen.png
  docs/sources/investigate/_index.md
  docs/sources/investigate/flame-graph-ai.md
  e2e/config/constants.ts
  e2e/tests/profile-types-view/profile-types.spec.ts
  src/README.md
  src/app/components/Onboarding/ui/NoDataSourcePage.tsx
  src/app/components/Onboarding/ui/OnboardingModal.tsx
  src/app/ui/ErrorPage.tsx
  src/img/hero-image-explore-profiles.png
  src/img/hero-image.png
  src/links.ts
  src/pages/ProfilesExplorerView/components/SceneLabelValuesTimeseries/SceneTimeseriesMenu.tsx
  src/pages/SettingsView/SettingsView.tsx
  src/plugin.json
  src/shared/ui/PluginInfo.tsx
Labels: feat

#410 feat: Add generated typed Pyroscope API client
  .github/workflows/build.yml
  .prettierignore
  buf.gen.yaml
  package.json
  src/shared/pyroscope-api/adhocprofiles/v1/adhocprofiles-AdHocProfileService_connectquery.ts
  src/shared/pyroscope-api/adhocprofiles/v1/adhocprofiles_pb.ts
  src/shared/pyroscope-api/google/v1/profile_pb.ts
  src/shared/pyroscope-api/querier/v1/querier-QuerierService_connectquery.ts
  src/shared/pyroscope-api/querier/v1/querier_pb.ts
  src/shared/pyroscope-api/settings/v1/setting-CollectionRulesService_connectquery.ts
  src/shared/pyroscope-api/settings/v1/setting-SettingsService_connectquery.ts
  src/shared/pyroscope-api/settings/v1/setting_pb.ts
  src/shared/pyroscope-api/types/v1/types_pb.ts
  src/shared/pyroscope-api/vcs/v1/vcs-VCSService_connectquery.ts
  src/shared/pyroscope-api/vcs/v1/vcs_pb.ts
  yarn.lock
Labels: feat

#437 chore: Update PR template
  .github/pull_request_template.md
Labels: chore

#434 ci: Add labels to CI jobs
  .github/workflows/ci.yml
  .github/workflows/cut-new-release.yml
Labels: ci
