Repository grafana/profiles-drilldown, pull requests merged in 2025-01, with the labels that each got.

#328 feat(GitHubIntegration): Add info tooltip on connect button
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneFunctionDetailsPanel/components/GitHubRepository.tsx
Labels: feat

#308 ci: Development workflow
  .drone.migration.jsonnet
  .github/workflows/ci.yml
  drone_migration.yaml
Labels: ci

#336 feat(FlameGraph): Keep items focused when data changes
  package.json
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/SceneFlameGraph.tsx
  src/shared/components/FlameGraph/FlameGraph.tsx
  yarn.lock
Labels: feat

#334 ci: Update sha in version.ts
  .github/workflows/ci.yml
Labels: ci

#337 chore(*): Auto-linting + Node v22 requirement
  .github/workflows/ci.yml
  docs/sources/access/profile-settings.md
  docs/sources/concepts/flame-graphs.md
  docs/sources/concepts/profile-types.md
  docs/sources/investigate/flame-graph-ai.md
  drone_migration.yaml
  package.json
Labels: chore

#340 chore(*): A couple of cosmetic fixes
  e2e/tests/profile-types-view/profile-types.spec.ts
  src/pages/ProfilesExplorerView/components/SceneAiPanel/components/AiButton/AIButton.tsx
  src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/components/Header.tsx
  src/pages/SettingsView/SettingsView.tsx
  src/shared/domain/reportInteraction.ts
Labels: chore

#344 ci: require running e2e before packaging
  .github/workflows/ci.yml
Labels: ci

#343 ci: permission to push tags
  .github/workflows/create-new-version.yml
Labels: ci

#345 ci: allow writing coverage report
  .github/workflows/ci.yml
Labels: ci

#349 chore(EndToEnd): Upgrade Playwright to v1.50.0
  Dockerfile.plugin.e2e
  package.json
  yarn.lock
Labels: chore

#355 fix(DiffFlameGraph): Always disable time ranges sync before applying a preset
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/SceneExploreDiffFlameGraph.tsx
Labels: fix

#356 ci(CreateNewVersion): Fix global URL
  .github/workflows/create-new-version.yml
Labels: ci

#357 ci(CreateNewVersion): create and push new tag
  .github/workflows/create-new-version.yml
Labels: ci

#358 ci: Use GitHub App in all actions
  .github/workflows/create-new-version.yml
Labels: ci

#347 fix(GitHubIntegration): Handle function details for inlining
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneFunctionDetailsPanel/domain/__tests__/convertPprofToFunctionDetails.spec.ts
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneFunctionDetailsPanel/domain/convertPprofToFunctionDetails.ts
  src/shared/types/PprofProfile.ts
Labels: fix

#359 fix(Grid): Fix error message display
  src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/SceneByVariableRepeaterGrid.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/components/SceneGroupByLabels/components/SceneLabelValuesGrid/SceneLabelValuesGrid.tsx
Labels: fix

#362 ci: Publish to catalog only when build is running in main
  .drone.jsonnet
  .drone.migration.jsonnet
  drone_migration.yaml
Labels: ci

#219 perf(Series): Limit the number of series request by breakdown charts
  docker-compose.e2e.yaml
  docker-compose.local.yaml
  docker-compose.remote.yaml
  docker-compose.yaml
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Panel-actions-Expand-panel-action-1-chromium-linux.png
  package.json
  src/pages/ProfilesExplorerView/components/SceneByVariableRepeaterGrid/infrastructure/data-transformations.ts
  src/pages/ProfilesExplorerView/components/SceneExploreFavorites/SceneExploreFavorites.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/components/SceneGroupByLabels/components/SceneLabelValuesGrid/SceneLabelValuesGrid.tsx
  src/pages/ProfilesExplorerView/components/SceneLabelValuesBarGauge.tsx
  src/pages/ProfilesExplorerView/components/SceneLabelValuesHistogram.tsx
  src/pages/ProfilesExplorerView/components/SceneLabelValuesTimeseries/SceneLabelValuesTimeseries.tsx
  src/pages/ProfilesExplorerView/infrastructure/timeseries/buildTimeSeriesQueryRunner.ts
  src/plugin.json
  src/shared/infrastructure/tracking/faro/__tests__/faro.spec.ts
  yarn.lock
Labels: perf, 🚫 blocked

#367 ci: Prevent signing and publishing the plugin in forked repos
  .github/workflows/ci.yml
Labels: ci

#372 ci: Remove unused GitHub action
  .github/workflows/plugin-release.yml
Labels: ci

#341 feat(LabelsView): update main time series when a "group by" label is selected
  e2e/fixtures/pages/ExploreProfilesPage.ts
  e2e/tests/all-services-view/all-services.spec.ts-snapshots/All-services-view-Panel-actions-Flame-graph-action-1-chromium-linux.png
  e2e/tests/all-services-view/all-services.spec.ts-snapshots/All-services-view-Panel-actions-Labels-action-1-chromium-linux.png
  e2e/tests/favorites-view/favorites-view.spec.ts-snapshots/Favorites-view-Panel-actions-Flame-graph-action-1-chromium-linux.png
  e2e/tests/favorites-view/favorites-view.spec.ts-snapshots/Favorites-view-Panel-actions-Labels-action-with-group-by-1-chromium-linux.png
  e2e/tests/favorites-view/favorites-view.spec.ts-snapshots/Favorites-view-Panel-actions-Labels-action-without-group-by-1-chromium-linux.png
  e2e/tests/flame-graph-view/flame-graph.spec.ts-snapshots/Flame-graph-view-Filters-Adding-a-filter-1-chromium-linux.png
  e2e/tests/flame-graph-view/flame-graph.spec.ts-snapshots/Flame-graph-view-Main-UI-elements-1-chromium-linux.png
  e2e/tests/flame-graph-view/flame-graph.spec.ts-snapshots/Flame-graph-view-Panel-actions-Labels-action-1-chromium-linux.png
  e2e/tests/flame-graph-view/flame-graph.spec.ts-snapshots/Flame-graph-view-Profile-type-selector-1-chromium-linux.png
  e2e/tests/flame-graph-view/flame-graph.spec.ts-snapshots/Flame-graph-view-Service-selector-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Filters-Adding-a-filter-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Group-by-labels-selector-After-sel-508a8-set-the-main-timeseries-Profile-type-selector-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Group-by-labels-selector-After-sel-c73f2-ch-reset-the-main-timeseries-Service-selector-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Group-by-labels-selector-After-selecting-a-label-Panel-actions-Flame-graph-action-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Main-UI-elements-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Panel-actions-Expand-panel-action-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Profile-type-selector-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Service-selector-1-chromium-linux.png
  e2e/tests/profile-types-view/profile-types.spec.ts-snapshots/Profile-types-view-Panel-actions-Flame-graph-action-1-chromium-linux.png
  e2e/tests/profile-types-view/profile-types.spec.ts-snapshots/Profile-types-view-Panel-actions-Labels-action-1-chromium-linux.png
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneComparePanel/SceneComparePanel.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/SceneExploreServiceLabels.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceLabels/components/SceneGroupByLabels/SceneGroupByLabels.tsx
  src/pages/ProfilesExplorerView/components/SceneLabelValuesTimeseries/SceneLabelValuesTimeseries.tsx
  src/pages/ProfilesExplorerView/components/SceneMainServiceTimeseries.tsx
  src/pages/ProfilesExplorerView/domain/variables/GroupByVariable/GroupByVariable.tsx
  src/pages/ProfilesExplorerView/infrastructure/labels/LabelsDataSource.ts
Labels: feat
