Repository grafana/profiles-drilldown, pull requests merged in 2025-04, with the labels that each got.

#480 fix: Get suggestions for optimize code
  package.json
  src/pages/ProfilesExplorerView/components/SceneAiPanel/components/AiReply.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneFunctionDetailsPanel/components/AiSuggestionsPanel/domain/buildLlmSuggestionPrompts.ts
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneFunctionDetailsPanel/components/AiSuggestionsPanel/domain/useOpenAiSuggestions.ts
  yarn.lock
Labels: fix

#474 fix(Settings): Reload settings when data source changes
  src/shared/infrastructure/settings/settingsApiClient.ts
  src/shared/infrastructure/settings/useFetchPluginSettings.ts
Labels: fix

#455 feat(CI): Append SHA to version number when releasing from main
  .github/workflows/build.yml
  .github/workflows/ci.yml
  .github/workflows/cut-new-release.yml
  .github/workflows/release-existing-version.yml
Labels: feat

#462 feat(Metrics): Basic UI for experimental metrics from profiles
  buf.gen.yaml
  e2e/fixtures/pages/ExploreProfilesPage.ts
  e2e/fixtures/pages/SettingsPage.ts
  e2e/tests/profile-types-view/profile-types.spec.ts
  e2e/tests/settings-view/settings-view.spec.ts
  package.json
  src/app/Routes.tsx
  src/constants.ts
  src/pages/AdHocView/AdHocView.tsx
  src/pages/ProfilesExplorerView/components/SceneCreateMetricModal/SceneCreateRecordingRuleModal.tsx
  src/pages/ProfilesExplorerView/components/SceneCreateMetricModal/domain/useCreateRecordingRule.ts
  src/pages/ProfilesExplorerView/components/SceneCreateMetricModal/domain/useMenuOption.ts
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/SceneFlameGraph.tsx
  src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/components/Header.tsx
  src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/components/domain/useHeader.ts
  src/pages/RecordingRulesView/DeleteRecordingRuleButton.tsx
  src/pages/RecordingRulesView/RecordingRulesView.tsx
  src/pages/RecordingRulesView/domain/useRecordingRulesView.ts
  src/pages/SettingsView/SettingsView.tsx
  src/pages/SettingsView/domain/__tests__/useSettingsView.spec.ts
  src/pages/SettingsView/domain/useSettingsView.ts
  src/shared/components/Common/BackButton.tsx
  src/shared/domain/reportInteraction.ts
  src/shared/infrastructure/recording-rules/recordingRulesApiClient.ts
  src/shared/infrastructure/recording-rules/useFetchRecordingRules.ts
  src/shared/infrastructure/settings/PluginSettings.ts
  src/shared/infrastructure/settings/featureToggles.ts
  src/shared/pyroscope-api/settings/v1/collection_rules-CollectionRulesService_connectquery.ts
  src/shared/pyroscope-api/settings/v1/collection_rules_pb.ts
  src/shared/pyroscope-api/settings/v1/recording_rules-RecordingRulesService_connectquery.ts
  src/shared/pyroscope-api/settings/v1/recording_rules_pb.ts
  src/shared/pyroscope-api/settings/v1/setting-SettingsService_connectquery.ts
  src/shared/pyroscope-api/settings/v1/setting_pb.ts
  src/shared/types/RecordingRuleViewModel.ts
  yarn.lock
Labels: feat

#484 fix: Cascader options break when services have multiple levels with matching prefix
  src/pages/ProfilesExplorerView/domain/variables/ServiceNameVariable/domain/__tests__/useBuildServiceNameOptions.spec.ts
  src/pages/ProfilesExplorerView/domain/variables/ServiceNameVariable/domain/useBuildServiceNameOptions.ts
Labels: fix

#491 chore: Update repo name references after the rename
  .github/workflows/publish-technical-documentation-next.yml
  .github/workflows/update-make-docs.yml
  README.md
  docs/CONTRIBUTING.md
  docs/GRAFANA-CROSS-DEVELOPMENT.md
  docs/README.md
  src/README.md
  src/plugin.json
  src/shared/components/QueryBuilder/ui/inputs/SingleEditionInput.tsx
  src/shared/ui/PluginInfo.tsx
Labels: chore

#493 chore(e2e): Update Playwright to 1.52.0
  Dockerfile.plugin.e2e
  package.json
  yarn.lock
Labels: chore

#504 chore(ci): Fix uploading artifacts
  .github/workflows/cut-new-release.yml
  .github/workflows/release-existing-version.yml
  .github/workflows/upload.yml
Labels: chore

#503 feat: Lazy load entire app
  src/app/Root.tsx
  src/module.ts
Labels: feat, upload
