Repository grafana/profiles-drilldown, pull requests merged in 2025-03, with the labels that each got.

#445 feat(FlameGraph): Show the flame graph for a selected span
  src/links.ts
  src/module.ts
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/SceneFlameGraph.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/SpanSelectorLabel.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/domain/events/RemoveSpanSelector.ts
  src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/SceneProfilesExplorer.tsx
  src/pages/ProfilesExplorerView/domain/variables/SpanSelectorVariable.tsx
  src/pages/ProfilesExplorerView/infrastructure/flame-graph/buildFlameGraphQueryRunner.ts
  src/plugin.json
Labels: feat

#451 chore(EndToEnd): Update Playwright to v1.51.0
  Dockerfile.plugin.e2e
  package.json
  yarn.lock
Labels: chore

#450 docs: Update the readme for Drilldown with proper navigation instructions
  README.md
Labels: type/docs

#453 docs: update app description
  src/plugin.json
Labels: type/docs

#454 docs: Fix label name for service_git_ref
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneFunctionDetailsPanel/ui/GitHubIntegrationBanner.tsx
Labels: type/docs

#459 fix(FlameGraph): Use entire file as context in "Optimize Code" prompt
  buf.gen.yaml
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneFunctionDetailsPanel/components/CodeContainer/CodeContainer.tsx
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneFunctionDetailsPanel/components/CodeContainer/domain/__tests__/annotateLines.spec.ts
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneFunctionDetailsPanel/components/CodeContainer/domain/__tests__/buildLineProfiles.spec.ts
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneFunctionDetailsPanel/components/CodeContainer/domain/annotateLines.ts
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneFunctionDetailsPanel/components/CodeContainer/domain/buildLineProfiles.ts
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneFunctionDetailsPanel/components/CodeContainer/domain/useCodeContainer.ts
Labels: fix

#447 feat: "profiling insights" extension
  src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/components/Header.tsx
  src/pages/ProfilesExplorerView/components/SceneProfilesExplorer/components/domain/useHeader.ts
  src/plugin.json
Labels: feat

#460 fix(llm): Add extra context in AI prompt about other lines in a file
  src/pages/ProfilesExplorerView/components/SceneExploreServiceFlameGraph/components/SceneFunctionDetailsPanel/components/AiSuggestionsPanel/domain/buildLlmSuggestionPrompts.ts
Labels: fix

#469 chore: Upgrade llm package
  package.json
  yarn.lock
Labels: chore

#461 chore: Add CODEOWNERS
  .github/CODEOWNERS
Labels: chore
