Repository grafana/profiles-drilldown, pull requests merged in 2025-09, with the labels that each got.

#578 ci: Add a workflow to publish a PR/branch
  .github/workflows/plugins-pr.yml
Labels: ci

#548 feat: Add rate calculation support and step synchronization
  e2e/tests/all-services-view/all-services.spec.ts-snapshots/All-services-view-Layout-switcher-1-chromium-linux.png
  e2e/tests/all-services-view/all-services.spec.ts-snapshots/All-services-view-Main-UI-elements-1-chromium-linux.png
  e2e/tests/all-services-view/all-services.spec.ts-snapshots/All-services-view-Panel-actions-Favorite-action-1-chromium-linux.png
  e2e/tests/all-services-view/all-services.spec.ts-snapshots/All-services-view-Panel-actions-Flame-graph-action-1-chromium-linux.png
  e2e/tests/all-services-view/all-services.spec.ts-snapshots/All-services-view-Panel-actions-Labels-action-1-chromium-linux.png
  e2e/tests/all-services-view/all-services.spec.ts-snapshots/All-services-view-Panel-actions-Profile-types-action-1-chromium-linux.png
  e2e/tests/all-services-view/all-services.spec.ts-snapshots/All-services-view-Profile-type-selector-1-chromium-linux.png
  e2e/tests/diff-flame-graph-view/diff-flame-graph.spec.ts-snapshots/Diff-flame-graph-view-Baseline-panel-Baseline-flame-graph-selection-mode-1-chromium-linux.png
  e2e/tests/diff-flame-graph-view/diff-flame-graph.spec.ts-snapshots/Diff-flame-graph-view-Baseline-panel-Baseline-time-picker-1-chromium-linux.png
  e2e/tests/diff-flame-graph-view/diff-flame-graph.spec.ts-snapshots/Diff-flame-graph-view-Baseline-panel-Baseline-time-picker-selection-mode-1-chromium-linux.png
  e2e/tests/diff-flame-graph-view/diff-flame-graph.spec.ts-snapshots/Diff-flame-graph-view-Comparison-panel-Comparison-flame-graph-selection-mode-1-chromium-linux.png
  e2e/tests/diff-flame-graph-view/diff-flame-graph.spec.ts-snapshots/Diff-flame-graph-view-Comparison-panel-Comparison-time-picker-1-chromium-linux.png
  e2e/tests/diff-flame-graph-view/diff-flame-graph.spec.ts-snapshots/Diff-flame-graph-view-Comparison-panel-Comparison-time-picker-selection-mode-1-chromium-linux.png
  e2e/tests/diff-flame-graph-view/diff-flame-graph.spec.ts-snapshots/Diff-flame-graph-view-Filters-Adding-a-filter-1-chromium-linux.png
  e2e/tests/diff-flame-graph-view/diff-flame-graph.spec.ts-snapshots/Diff-flame-graph-view-Main-UI-elements-1-chromium-linux.png
  e2e/tests/diff-flame-graph-view/diff-flame-graph.spec.ts-snapshots/Diff-flame-graph-view-Profile-type-selector-1-chromium-linux.png
  e2e/tests/diff-flame-graph-view/diff-flame-graph.spec.ts-snapshots/Diff-flame-graph-view-Service-selector-1-chromium-linux.png
  e2e/tests/diff-flame-graph-view/diff-flame-graph.spec.ts-snapshots/Diff-flame-graph-view-Sync-time-ranges-Syncing-flame-graph-range-selection-1-chromium-linux.png
  e2e/tests/diff-flame-graph-view/diff-flame-graph.spec.ts-snapshots/Diff-flame-graph-view-Sync-time-ranges-Syncing-time-picker-range-selection-1-chromium-linux.png
  e2e/tests/favorites-view/favorites-view.spec.ts-snapshots/Favorites-view-Layout-switcher-1-chromium-linux.png
  e2e/tests/favorites-view/favorites-view.spec.ts-snapshots/Favorites-view-Main-UI-elements-1-chromium-linux.png
  e2e/tests/favorites-view/favorites-view.spec.ts-snapshots/Favorites-view-Panel-actions-Expand-panel-action-1-chromium-linux.png
  e2e/tests/favorites-view/favorites-view.spec.ts-snapshots/Favorites-view-Panel-actions-Flame-graph-action-1-chromium-linux.png
  e2e/tests/favorites-view/favorites-view.spec.ts-snapshots/Favorites-view-Panel-actions-Labels-action-with-group-by-1-chromium-linux.png
  e2e/tests/favorites-view/favorites-view.spec.ts-snapshots/Favorites-view-Panel-actions-Labels-action-without-group-by-1-chromium-linux.png
  e2e/tests/flame-graph-view/flame-graph.spec.ts-snapshots/Flame-graph-view-Filters-Adding-a-filter-1-chromium-linux.png
  e2e/tests/flame-graph-view/flame-graph.spec.ts-snapshots/Flame-graph-view-Main-UI-elements-1-chromium-linux.png
  e2e/tests/flame-graph-view/flame-graph.spec.ts-snapshots/Flame-graph-view-Panel-actions-Favorite-action-1-chromium-linux.png
  e2e/tests/flame-graph-view/flame-graph.spec.ts-snapshots/Flame-graph-view-Panel-actions-Labels-action-1-chromium-linux.png
  e2e/tests/flame-graph-view/flame-graph.spec.ts-snapshots/Flame-graph-view-Profile-type-selector-1-chromium-linux.png
  e2e/tests/flame-graph-view/flame-graph.spec.ts-snapshots/Flame-graph-view-Service-selector-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Filters-Adding-a-filter-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Group-by-labels-selector-After-sel-508a8-set-the-main-timeseries-Profile-type-selector-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Group-by-labels-selector-After-sel-c73f2-ch-reset-the-main-timeseries-Service-selector-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Group-by-labels-selector-After-sel-dbe5f-n-items-then-clicking-on-the-Compare-button-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Group-by-labels-selector-After-sel-f81f2-on-item-then-clicking-on-the-Compare-button-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Group-by-labels-selector-After-selecting-a-label-Panel-actions-Flame-graph-action-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Layout-switcher-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Main-UI-elements-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Panel-actions-Expand-panel-action-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Panel-type-switcher-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Panel-type-switcher-2-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Panel-type-switcher-3-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Profile-type-selector-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Service-selector-1-chromium-linux.png
  e2e/tests/profile-types-view/profile-types.spec.ts-snapshots/Profile-types-view-Layout-switcher-1-chromium-linux.png
  e2e/tests/profile-types-view/profile-types.spec.ts-snapshots/Profile-types-view-Main-UI-elements-1-chromium-linux.png
  e2e/tests/profile-types-view/profile-types.spec.ts-snapshots/Profile-types-view-Panel-actions-Favorite-action-1-chromium-linux.png
  e2e/tests/profile-types-view/profile-types.spec.ts-snapshots/Profile-types-view-Panel-actions-Flame-graph-action-1-chromium-linux.png
  e2e/tests/profile-types-view/profile-types.spec.ts-snapshots/Profile-types-view-Panel-actions-Labels-action-1-chromium-linux.png
  e2e/tests/profile-types-view/profile-types.spec.ts-snapshots/Profile-types-view-Service-selector-1-chromium-linux.png
  e2e/tests/profile-types-view/profile-types.spec.ts-snapshots/Profile-types-view-Settings-button-1-chromium-linux.png
  src/pages/ProfilesExplorerView/components/SceneExploreDiffFlameGraph/components/SceneComparePanel/SceneComparePanel.tsx
  src/pages/ProfilesExplorerView/components/SceneLabelValuesTable.tsx
  src/pages/ProfilesExplorerView/components/SceneLabelValuesTimeseries/SceneLabelValuesTimeseries.tsx
  src/pages/ProfilesExplorerView/helpers/formatSingleSeriesDisplayName.ts
  src/shared/infrastructure/profile-metrics/profile-metrics.json
Labels: feat

#600 ci: Deploy automatically to ops
  .github/workflows/plugins-ci.yml
Labels: ci

#604 chore(e2e): Upgrade Playwright to 1.55.1
  .config/docker-compose-base.yaml
  .github/workflows/plugins-ci.yml
  .github/workflows/plugins-pr.yml
  .github/workflows/plugins-release.yml
  Dockerfile.plugin.e2e
  docker-compose.e2e.yaml
  docker-compose.remote.yaml
  docker-compose.yaml
  e2e/tests/ad-hoc-view/ad-hoc-view.spec.ts-snapshots/Single-view-uploads-Multiple-profile-types-Pprof-uploads-1-chromium-linux.png
  e2e/tests/ad-hoc-view/ad-hoc-view.spec.ts-snapshots/Single-view-uploads-Multiple-profile-types-Pprof-uploads-2-chromium-linux.png
  e2e/tests/ad-hoc-view/ad-hoc-view.spec.ts-snapshots/Single-view-uploads-Multiple-profile-types-Pprof-uploads-3-chromium-linux.png
  e2e/tests/ad-hoc-view/ad-hoc-view.spec.ts-snapshots/Single-view-uploads-Single-profile-type-Gzipped-Pprof-uploads-1-chromium-linux.png
  e2e/tests/ad-hoc-view/ad-hoc-view.spec.ts-snapshots/Single-view-uploads-Single-profile-type-Pprof-uploads-1-chromium-linux.png
  e2e/tests/favorites-view/favorites-view.spec.ts-snapshots/Favorites-view-Main-UI-elements-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Group-by-labels-selector-Selects-a-label-and-displays-the-breakdown-in-a-new-grid-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Panel-actions-Expand-panel-action-1-chromium-linux.png
  e2e/tests/labels-view/labels.spec.ts-snapshots/Labels-view-Panel-actions-Select-action-1-chromium-linux.png
  package.json
  yarn.lock
Labels: chore

#605 chore: Add missing target to plugin.json
  src/plugin.json
Labels: chore
